// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: artery/voting/v1beta1/args.proto

package types

import (
	fmt "fmt"
	github_com_arterynetwork_artr_util "github.com/arterynetwork/artr/util"
	types "github.com/arterynetwork/artr/x/delegating/types"
	types2 "github.com/arterynetwork/artr/x/noding/types"
	types1 "github.com/arterynetwork/artr/x/referral/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PriceArgs struct {
	Price uint32 `protobuf:"varint,1,opt,name=price,proto3" json:"price" yaml:"price"`
}

func (m *PriceArgs) Reset()         { *m = PriceArgs{} }
func (m *PriceArgs) String() string { return proto.CompactTextString(m) }
func (*PriceArgs) ProtoMessage()    {}
func (*PriceArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{0}
}
func (m *PriceArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceArgs.Merge(m, src)
}
func (m *PriceArgs) XXX_Size() int {
	return m.Size()
}
func (m *PriceArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PriceArgs proto.InternalMessageInfo

func (m *PriceArgs) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

// Deprecated: Do not use.
type DelegationAwardArgs struct {
	Award types.Percentage `protobuf:"bytes,1,opt,name=award,proto3" json:"award" yaml:"award"`
}

func (m *DelegationAwardArgs) Reset()         { *m = DelegationAwardArgs{} }
func (m *DelegationAwardArgs) String() string { return proto.CompactTextString(m) }
func (*DelegationAwardArgs) ProtoMessage()    {}
func (*DelegationAwardArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{1}
}
func (m *DelegationAwardArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationAwardArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationAwardArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationAwardArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationAwardArgs.Merge(m, src)
}
func (m *DelegationAwardArgs) XXX_Size() int {
	return m.Size()
}
func (m *DelegationAwardArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationAwardArgs.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationAwardArgs proto.InternalMessageInfo

func (m *DelegationAwardArgs) GetAward() types.Percentage {
	if m != nil {
		return m.Award
	}
	return types.Percentage{}
}

// Deprecated: Do not use.
type NetworkAwardArgs struct {
	Award types1.NetworkAward `protobuf:"bytes,1,opt,name=award,proto3" json:"award" yaml:"award"`
}

func (m *NetworkAwardArgs) Reset()         { *m = NetworkAwardArgs{} }
func (m *NetworkAwardArgs) String() string { return proto.CompactTextString(m) }
func (*NetworkAwardArgs) ProtoMessage()    {}
func (*NetworkAwardArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{2}
}
func (m *NetworkAwardArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkAwardArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetworkAwardArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetworkAwardArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAwardArgs.Merge(m, src)
}
func (m *NetworkAwardArgs) XXX_Size() int {
	return m.Size()
}
func (m *NetworkAwardArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAwardArgs.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAwardArgs proto.InternalMessageInfo

func (m *NetworkAwardArgs) GetAward() types1.NetworkAward {
	if m != nil {
		return m.Award
	}
	return types1.NetworkAward{}
}

type AddressArgs struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address" yaml:"address"`
}

func (m *AddressArgs) Reset()         { *m = AddressArgs{} }
func (m *AddressArgs) String() string { return proto.CompactTextString(m) }
func (*AddressArgs) ProtoMessage()    {}
func (*AddressArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{3}
}
func (m *AddressArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressArgs.Merge(m, src)
}
func (m *AddressArgs) XXX_Size() int {
	return m.Size()
}
func (m *AddressArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AddressArgs proto.InternalMessageInfo

type SoftwareUpgradeArgs struct {
	// Name - upgrade name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	// Height - block height to schedule the upgrade at
	// DEPRECATED: Use Time instead
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty" yaml:"height,omitempty"`
	// Info - a link (with a checksum) to a JSON file containing upgrade data (binary URIs and so on)
	// Please refer to https://github.com/regen-network/cosmosd#auto-download
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info" yaml:"info"`
	// Time the upgrade is scheduled at
	Time *time.Time `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time,omitempty" yaml:"time,omitempty"`
}

func (m *SoftwareUpgradeArgs) Reset()         { *m = SoftwareUpgradeArgs{} }
func (m *SoftwareUpgradeArgs) String() string { return proto.CompactTextString(m) }
func (*SoftwareUpgradeArgs) ProtoMessage()    {}
func (*SoftwareUpgradeArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{4}
}
func (m *SoftwareUpgradeArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SoftwareUpgradeArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SoftwareUpgradeArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SoftwareUpgradeArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoftwareUpgradeArgs.Merge(m, src)
}
func (m *SoftwareUpgradeArgs) XXX_Size() int {
	return m.Size()
}
func (m *SoftwareUpgradeArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SoftwareUpgradeArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SoftwareUpgradeArgs proto.InternalMessageInfo

func (m *SoftwareUpgradeArgs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SoftwareUpgradeArgs) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SoftwareUpgradeArgs) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *SoftwareUpgradeArgs) GetTime() *time.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type MinAmountArgs struct {
	MinAmount int64 `protobuf:"varint,1,opt,name=min_amount,json=minAmount,proto3" json:"min_amount" yaml:"min_amount"`
}

func (m *MinAmountArgs) Reset()         { *m = MinAmountArgs{} }
func (m *MinAmountArgs) String() string { return proto.CompactTextString(m) }
func (*MinAmountArgs) ProtoMessage()    {}
func (*MinAmountArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{5}
}
func (m *MinAmountArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinAmountArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MinAmountArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MinAmountArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinAmountArgs.Merge(m, src)
}
func (m *MinAmountArgs) XXX_Size() int {
	return m.Size()
}
func (m *MinAmountArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_MinAmountArgs.DiscardUnknown(m)
}

var xxx_messageInfo_MinAmountArgs proto.InternalMessageInfo

func (m *MinAmountArgs) GetMinAmount() int64 {
	if m != nil {
		return m.MinAmount
	}
	return 0
}

type CountArgs struct {
	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count" yaml:"count"`
}

func (m *CountArgs) Reset()         { *m = CountArgs{} }
func (m *CountArgs) String() string { return proto.CompactTextString(m) }
func (*CountArgs) ProtoMessage()    {}
func (*CountArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{6}
}
func (m *CountArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CountArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CountArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CountArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountArgs.Merge(m, src)
}
func (m *CountArgs) XXX_Size() int {
	return m.Size()
}
func (m *CountArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CountArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CountArgs proto.InternalMessageInfo

func (m *CountArgs) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Deprecated: Do not use.
type StatusArgs struct {
	Status types1.Status `protobuf:"varint,1,opt,name=status,proto3,enum=artery.referral.v1beta1.Status" json:"status" yaml:"status"`
}

func (m *StatusArgs) Reset()         { *m = StatusArgs{} }
func (m *StatusArgs) String() string { return proto.CompactTextString(m) }
func (*StatusArgs) ProtoMessage()    {}
func (*StatusArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{7}
}
func (m *StatusArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatusArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatusArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatusArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusArgs.Merge(m, src)
}
func (m *StatusArgs) XXX_Size() int {
	return m.Size()
}
func (m *StatusArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StatusArgs proto.InternalMessageInfo

func (m *StatusArgs) GetStatus() types1.Status {
	if m != nil {
		return m.Status
	}
	return types1.STATUS_UNSPECIFIED
}

type MinCriteriaArgs struct {
	MinCriteria *types2.MinCriteria `protobuf:"bytes,1,opt,name=min_criteria,json=minCriteria,proto3" json:"min_criteria,omitempty"`
}

func (m *MinCriteriaArgs) Reset()         { *m = MinCriteriaArgs{} }
func (m *MinCriteriaArgs) String() string { return proto.CompactTextString(m) }
func (*MinCriteriaArgs) ProtoMessage()    {}
func (*MinCriteriaArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{8}
}
func (m *MinCriteriaArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MinCriteriaArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MinCriteriaArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MinCriteriaArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinCriteriaArgs.Merge(m, src)
}
func (m *MinCriteriaArgs) XXX_Size() int {
	return m.Size()
}
func (m *MinCriteriaArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_MinCriteriaArgs.DiscardUnknown(m)
}

var xxx_messageInfo_MinCriteriaArgs proto.InternalMessageInfo

func (m *MinCriteriaArgs) GetMinCriteria() *types2.MinCriteria {
	if m != nil {
		return m.MinCriteria
	}
	return nil
}

// Deprecated: Do not use.
type PeriodArgs struct {
	Days uint32 `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
}

func (m *PeriodArgs) Reset()         { *m = PeriodArgs{} }
func (m *PeriodArgs) String() string { return proto.CompactTextString(m) }
func (*PeriodArgs) ProtoMessage()    {}
func (*PeriodArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{9}
}
func (m *PeriodArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PeriodArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PeriodArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PeriodArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodArgs.Merge(m, src)
}
func (m *PeriodArgs) XXX_Size() int {
	return m.Size()
}
func (m *PeriodArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodArgs proto.InternalMessageInfo

func (m *PeriodArgs) GetDays() uint32 {
	if m != nil {
		return m.Days
	}
	return 0
}

type PortionArgs struct {
	Fraction github_com_arterynetwork_artr_util.Fraction `protobuf:"bytes,1,opt,name=Fraction,proto3,customtype=github.com/arterynetwork/artr/util.Fraction" json:"fraction" yaml:"fraction"`
}

func (m *PortionArgs) Reset()         { *m = PortionArgs{} }
func (m *PortionArgs) String() string { return proto.CompactTextString(m) }
func (*PortionArgs) ProtoMessage()    {}
func (*PortionArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{10}
}
func (m *PortionArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PortionArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PortionArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PortionArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortionArgs.Merge(m, src)
}
func (m *PortionArgs) XXX_Size() int {
	return m.Size()
}
func (m *PortionArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PortionArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PortionArgs proto.InternalMessageInfo

type PortionsArgs struct {
	Fractions []github_com_arterynetwork_artr_util.Fraction `protobuf:"bytes,1,rep,name=Fractions,proto3,customtype=github.com/arterynetwork/artr/util.Fraction" json:"fractions" yaml:"fractions"`
}

func (m *PortionsArgs) Reset()         { *m = PortionsArgs{} }
func (m *PortionsArgs) String() string { return proto.CompactTextString(m) }
func (*PortionsArgs) ProtoMessage()    {}
func (*PortionsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{11}
}
func (m *PortionsArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PortionsArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PortionsArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PortionsArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortionsArgs.Merge(m, src)
}
func (m *PortionsArgs) XXX_Size() int {
	return m.Size()
}
func (m *PortionsArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PortionsArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PortionsArgs proto.InternalMessageInfo

// Deprecated: Do not use.
type AccruePercentageRangesArgs struct {
	AccruePercentageRanges []types.PercentageRange `protobuf:"bytes,1,rep,name=accrue_percentage_ranges,json=accruePercentageRanges,proto3" json:"accrue_percentage_ranges"`
}

func (m *AccruePercentageRangesArgs) Reset()         { *m = AccruePercentageRangesArgs{} }
func (m *AccruePercentageRangesArgs) String() string { return proto.CompactTextString(m) }
func (*AccruePercentageRangesArgs) ProtoMessage()    {}
func (*AccruePercentageRangesArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{12}
}
func (m *AccruePercentageRangesArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccruePercentageRangesArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccruePercentageRangesArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccruePercentageRangesArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccruePercentageRangesArgs.Merge(m, src)
}
func (m *AccruePercentageRangesArgs) XXX_Size() int {
	return m.Size()
}
func (m *AccruePercentageRangesArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AccruePercentageRangesArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AccruePercentageRangesArgs proto.InternalMessageInfo

func (m *AccruePercentageRangesArgs) GetAccruePercentageRanges() []types.PercentageRange {
	if m != nil {
		return m.AccruePercentageRanges
	}
	return nil
}

type AccruePercentageTableArgs struct {
	AccruePercentageTable []types.PercentageListRange `protobuf:"bytes,1,rep,name=accrue_percentage_table,json=accruePercentageTable,proto3" json:"accrue_percentage_table"`
}

func (m *AccruePercentageTableArgs) Reset()         { *m = AccruePercentageTableArgs{} }
func (m *AccruePercentageTableArgs) String() string { return proto.CompactTextString(m) }
func (*AccruePercentageTableArgs) ProtoMessage()    {}
func (*AccruePercentageTableArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{13}
}
func (m *AccruePercentageTableArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccruePercentageTableArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccruePercentageTableArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccruePercentageTableArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccruePercentageTableArgs.Merge(m, src)
}
func (m *AccruePercentageTableArgs) XXX_Size() int {
	return m.Size()
}
func (m *AccruePercentageTableArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AccruePercentageTableArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AccruePercentageTableArgs proto.InternalMessageInfo

func (m *AccruePercentageTableArgs) GetAccruePercentageTable() []types.PercentageListRange {
	if m != nil {
		return m.AccruePercentageTable
	}
	return nil
}

type RevokeArgs struct {
	Revoke *types.Revoke `protobuf:"bytes,1,opt,name=revoke,proto3" json:"revoke,omitempty"`
}

func (m *RevokeArgs) Reset()         { *m = RevokeArgs{} }
func (m *RevokeArgs) String() string { return proto.CompactTextString(m) }
func (*RevokeArgs) ProtoMessage()    {}
func (*RevokeArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47802f3a280afb6, []int{14}
}
func (m *RevokeArgs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevokeArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevokeArgs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevokeArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeArgs.Merge(m, src)
}
func (m *RevokeArgs) XXX_Size() int {
	return m.Size()
}
func (m *RevokeArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeArgs proto.InternalMessageInfo

func (m *RevokeArgs) GetRevoke() *types.Revoke {
	if m != nil {
		return m.Revoke
	}
	return nil
}

func init() {
	proto.RegisterType((*PriceArgs)(nil), "artery.voting.v1beta1.PriceArgs")
	proto.RegisterType((*DelegationAwardArgs)(nil), "artery.voting.v1beta1.DelegationAwardArgs")
	proto.RegisterType((*NetworkAwardArgs)(nil), "artery.voting.v1beta1.NetworkAwardArgs")
	proto.RegisterType((*AddressArgs)(nil), "artery.voting.v1beta1.AddressArgs")
	proto.RegisterType((*SoftwareUpgradeArgs)(nil), "artery.voting.v1beta1.SoftwareUpgradeArgs")
	proto.RegisterType((*MinAmountArgs)(nil), "artery.voting.v1beta1.MinAmountArgs")
	proto.RegisterType((*CountArgs)(nil), "artery.voting.v1beta1.CountArgs")
	proto.RegisterType((*StatusArgs)(nil), "artery.voting.v1beta1.StatusArgs")
	proto.RegisterType((*MinCriteriaArgs)(nil), "artery.voting.v1beta1.MinCriteriaArgs")
	proto.RegisterType((*PeriodArgs)(nil), "artery.voting.v1beta1.PeriodArgs")
	proto.RegisterType((*PortionArgs)(nil), "artery.voting.v1beta1.PortionArgs")
	proto.RegisterType((*PortionsArgs)(nil), "artery.voting.v1beta1.PortionsArgs")
	proto.RegisterType((*AccruePercentageRangesArgs)(nil), "artery.voting.v1beta1.AccruePercentageRangesArgs")
	proto.RegisterType((*AccruePercentageTableArgs)(nil), "artery.voting.v1beta1.AccruePercentageTableArgs")
	proto.RegisterType((*RevokeArgs)(nil), "artery.voting.v1beta1.RevokeArgs")
}

func init() { proto.RegisterFile("artery/voting/v1beta1/args.proto", fileDescriptor_d47802f3a280afb6) }

var fileDescriptor_d47802f3a280afb6 = []byte{
	// 922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0x36, 0x8e, 0x89, 0x9f, 0x93, 0x34, 0xb8, 0x84, 0xb8, 0x46, 0xf5, 0xa4, 0x5b, 0x8a,
	0x22, 0x5a, 0xed, 0xaa, 0xe9, 0x01, 0x91, 0x9b, 0xb7, 0x50, 0x2e, 0x04, 0x59, 0xd3, 0x70, 0xa0,
	0x07, 0xa2, 0xf1, 0x7a, 0xbc, 0xd9, 0xd6, 0xbb, 0x63, 0x8d, 0xc7, 0x0e, 0x3e, 0x73, 0xe9, 0x8d,
	0xfc, 0x09, 0x95, 0xf8, 0x67, 0x72, 0xec, 0x11, 0x71, 0x18, 0x50, 0x72, 0x41, 0x3e, 0xfa, 0x2f,
	0x40, 0xf3, 0x63, 0x77, 0xed, 0xd2, 0x94, 0xc0, 0x6d, 0xbf, 0x37, 0xef, 0x7d, 0xdf, 0x37, 0x6f,
	0xe6, 0x8d, 0x0d, 0xbb, 0x84, 0x0b, 0xca, 0xa7, 0xfe, 0x84, 0x89, 0x38, 0x8d, 0xfc, 0xc9, 0xa3,
	0x2e, 0x15, 0xe4, 0x91, 0x4f, 0x78, 0x34, 0xf2, 0x86, 0x9c, 0x09, 0x56, 0xdf, 0x36, 0x19, 0x9e,
	0xc9, 0xf0, 0x6c, 0x46, 0xf3, 0xa3, 0x88, 0x45, 0x4c, 0x67, 0xf8, 0xea, 0xcb, 0x24, 0x37, 0x51,
	0xc4, 0x58, 0x34, 0xa0, 0xbe, 0x46, 0xdd, 0x71, 0xdf, 0x17, 0x71, 0x42, 0x47, 0x82, 0x24, 0x43,
	0x9b, 0x70, 0xd7, 0xea, 0xa5, 0xac, 0xb7, 0xa8, 0x27, 0xa6, 0x43, 0x6a, 0x05, 0x9b, 0x9f, 0xda,
	0x14, 0x4e, 0xfb, 0x94, 0x73, 0x32, 0xc8, 0x93, 0x86, 0x84, 0x93, 0x24, 0xcb, 0xba, 0x77, 0x55,
	0xd6, 0x22, 0xd5, 0x67, 0x36, 0xa9, 0x47, 0x07, 0x34, 0x22, 0x4b, 0x3b, 0x5c, 0x22, 0xbb, 0x7f,
	0x75, 0xde, 0x02, 0x9d, 0x1b, 0x40, 0xb5, 0xc3, 0xe3, 0x90, 0xb6, 0x79, 0x34, 0xaa, 0xfb, 0xb0,
	0x3a, 0x54, 0xa0, 0xe1, 0xec, 0x3a, 0x7b, 0x1b, 0xc1, 0xed, 0x99, 0x44, 0x26, 0x30, 0x97, 0x68,
	0x7d, 0x4a, 0x92, 0xc1, 0x81, 0xab, 0xa1, 0x8b, 0x4d, 0xf8, 0xa0, 0xfc, 0xd7, 0x6b, 0xe4, 0xb8,
	0x53, 0xb8, 0xf5, 0x95, 0x55, 0x61, 0x69, 0xfb, 0x94, 0xf0, 0x9e, 0x66, 0x7b, 0x0e, 0xab, 0x44,
	0x01, 0xcd, 0x56, 0xdb, 0xbf, 0xef, 0xd9, 0xae, 0x17, 0x8e, 0xb2, 0xce, 0x7b, 0x1d, 0xca, 0x43,
	0x9a, 0x0a, 0x12, 0xd1, 0xe0, 0xce, 0xb9, 0x44, 0x25, 0x25, 0xac, 0x6b, 0x0b, 0x61, 0x0d, 0x5d,
	0x6c, 0xc2, 0x07, 0x15, 0x25, 0xdc, 0x70, 0xdc, 0x09, 0x6c, 0x7d, 0x47, 0xc5, 0x29, 0xe3, 0x2f,
	0xff, 0x5d, 0x37, 0x6b, 0x6b, 0xae, 0xba, 0x58, 0xf9, 0x1f, 0x75, 0x3b, 0x50, 0x6b, 0xf7, 0x7a,
	0x9c, 0x8e, 0x46, 0x5a, 0xf2, 0x0b, 0xf8, 0x80, 0x18, 0xa8, 0x45, 0xab, 0xc1, 0x9d, 0x99, 0x44,
	0x59, 0x68, 0x2e, 0xd1, 0xa6, 0xe5, 0x32, 0x01, 0x17, 0x67, 0x4b, 0x07, 0x6b, 0xaf, 0x5e, 0xa3,
	0x92, 0x6e, 0xe2, 0xaf, 0x37, 0xe0, 0xd6, 0x33, 0xd6, 0x17, 0xa7, 0x84, 0xd3, 0xef, 0x87, 0x11,
	0x27, 0x3d, 0x73, 0x26, 0x0f, 0xa0, 0x9c, 0x92, 0x84, 0x5a, 0xde, 0x9d, 0x99, 0x44, 0x1a, 0xcf,
	0x25, 0xaa, 0x19, 0x52, 0x85, 0x5c, 0xac, 0x83, 0xf5, 0x6f, 0xa0, 0x72, 0x42, 0xe3, 0xe8, 0x44,
	0x34, 0x6e, 0xec, 0x3a, 0x7b, 0x2b, 0x81, 0x3f, 0x93, 0x68, 0xcb, 0x44, 0x1e, 0xb2, 0x24, 0x16,
	0x34, 0x19, 0x8a, 0xe9, 0x5c, 0xa2, 0x1d, 0x53, 0xfa, 0xf6, 0x8a, 0x8b, 0x6d, 0xb9, 0x52, 0x8d,
	0xd3, 0x3e, 0x6b, 0xac, 0x14, 0xaa, 0x0a, 0x17, 0xaa, 0x0a, 0xb9, 0x58, 0x07, 0xeb, 0x21, 0x94,
	0xd5, 0x4c, 0x34, 0xca, 0xba, 0xdf, 0x4d, 0xcf, 0x0c, 0x8c, 0x97, 0x0d, 0x8c, 0x77, 0x94, 0x0d,
	0x4c, 0xf0, 0xf8, 0x5c, 0x22, 0x67, 0x26, 0xd1, 0xa6, 0xca, 0x5f, 0x72, 0xb4, 0x6d, 0x68, 0x97,
	0xe3, 0xee, 0xd9, 0x1f, 0xc8, 0xc1, 0x9a, 0xdc, 0x5e, 0xb5, 0x1f, 0x60, 0xe3, 0x30, 0x4e, 0xdb,
	0x09, 0x1b, 0xa7, 0x42, 0xb7, 0x27, 0x00, 0x48, 0xe2, 0xf4, 0x98, 0xe8, 0x88, 0x6e, 0xd2, 0x4a,
	0x70, 0x6f, 0x26, 0xd1, 0x42, 0x74, 0x2e, 0xd1, 0x87, 0x86, 0xbd, 0x88, 0xb9, 0xb8, 0x9a, 0x64,
	0x3c, 0x96, 0x3a, 0x80, 0xea, 0x93, 0x9c, 0xd6, 0x87, 0xd5, 0x30, 0x67, 0xb4, 0x93, 0x10, 0x5a,
	0x32, 0x7b, 0x31, 0x42, 0xc3, 0x63, 0xc2, 0x96, 0xe3, 0x05, 0xc0, 0x33, 0x41, 0xc4, 0xd8, 0xdc,
	0x8a, 0x23, 0xa8, 0x8c, 0x34, 0xd2, 0x2c, 0x9b, 0xfb, 0xe8, 0xca, 0x9b, 0x68, 0x8a, 0x82, 0x4f,
	0x66, 0x12, 0xd9, 0x92, 0xb9, 0x44, 0x1b, 0x46, 0xc7, 0x60, 0x17, 0xdb, 0x85, 0xfc, 0x0a, 0xfe,
	0x08, 0x37, 0x0f, 0xe3, 0xf4, 0x09, 0x8f, 0x05, 0xe5, 0x31, 0xd1, 0x82, 0x5f, 0xc3, 0xba, 0xda,
	0x62, 0x68, 0x63, 0x76, 0x00, 0xdc, 0x4c, 0xd6, 0x3c, 0x50, 0xb9, 0xe8, 0x42, 0x35, 0xae, 0x25,
	0x05, 0xb0, 0x7b, 0xd9, 0x03, 0xe8, 0x50, 0x1e, 0x33, 0x33, 0x54, 0x75, 0x28, 0xf7, 0xc8, 0xd4,
	0xec, 0x64, 0x03, 0xeb, 0xef, 0xdc, 0xc9, 0xcf, 0x0e, 0xd4, 0x3a, 0x8c, 0xeb, 0xe9, 0x57, 0xb9,
	0x29, 0xac, 0x3d, 0xe5, 0x24, 0x54, 0xd8, 0x5e, 0x5b, 0xac, 0x86, 0xeb, 0x77, 0x89, 0x1e, 0x44,
	0xb1, 0x38, 0x19, 0x77, 0xbd, 0x90, 0x25, 0xbe, 0x31, 0x95, 0x9a, 0x19, 0x54, 0x88, 0xfb, 0x63,
	0x11, 0x0f, 0xbc, 0xac, 0x74, 0x26, 0xd1, 0x5a, 0xdf, 0x7e, 0xcf, 0x25, 0xba, 0x69, 0xba, 0x91,
	0x45, 0x5c, 0x9c, 0x6b, 0x58, 0xbf, 0xaf, 0x1c, 0x58, 0xb7, 0x2e, 0x4c, 0xfb, 0x39, 0x54, 0xb3,
	0x14, 0xe5, 0x7b, 0x65, 0xaf, 0x1a, 0x1c, 0xfd, 0x3f, 0x1f, 0xd5, 0x4c, 0x55, 0x1d, 0xcb, 0xd6,
	0xb2, 0x91, 0x91, 0x8b, 0x0b, 0x19, 0x6b, 0xe5, 0xcc, 0x81, 0x66, 0x3b, 0x0c, 0xf9, 0x98, 0x16,
	0x0f, 0x1b, 0x26, 0x69, 0x44, 0x8d, 0xb1, 0x17, 0xd0, 0x20, 0x7a, 0xf5, 0x78, 0x98, 0x2f, 0x1f,
	0x73, 0xbd, 0xae, 0x7d, 0xd6, 0xf6, 0x3f, 0xbf, 0xd6, 0x5b, 0xa9, 0x29, 0x83, 0xb2, 0xda, 0x13,
	0xfe, 0x98, 0xbc, 0x53, 0x2f, 0x3f, 0xa3, 0x5f, 0x1c, 0xb8, 0xfd, 0xb6, 0xa5, 0x23, 0xd2, 0x1d,
	0x98, 0x47, 0x66, 0x00, 0x3b, 0xff, 0x74, 0x24, 0xd4, 0xb2, 0x35, 0xe4, 0x5d, 0xcb, 0xd0, 0xb7,
	0xf1, 0x48, 0x2c, 0x9a, 0xda, 0x26, 0xef, 0x52, 0xb4, 0x4d, 0x3a, 0x04, 0xc0, 0x74, 0xc2, 0x5e,
	0x1a, 0x07, 0x5f, 0x42, 0x85, 0x6b, 0x64, 0x2f, 0xed, 0xdd, 0xf7, 0x08, 0x9a, 0x32, 0x6c, 0x0b,
	0x0c, 0x5d, 0xf0, 0xf4, 0xfc, 0xa2, 0xe5, 0xbc, 0xb9, 0x68, 0x39, 0x7f, 0x5e, 0xb4, 0x9c, 0xb3,
	0xcb, 0x56, 0xe9, 0xcd, 0x65, 0xab, 0xf4, 0xdb, 0x65, 0xab, 0xf4, 0xfc, 0xe1, 0xfb, 0x0f, 0xfb,
	0xa7, 0xec, 0x8f, 0x82, 0xfe, 0x59, 0xec, 0x56, 0xf4, 0xb3, 0xf5, 0xf8, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xba, 0x2d, 0x76, 0x1f, 0x46, 0x08, 0x00, 0x00,
}

func (this *PriceArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PriceArgs)
	if !ok {
		that2, ok := that.(PriceArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Price != that1.Price {
		return false
	}
	return true
}
func (this *DelegationAwardArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DelegationAwardArgs)
	if !ok {
		that2, ok := that.(DelegationAwardArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Award.Equal(&that1.Award) {
		return false
	}
	return true
}
func (this *NetworkAwardArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*NetworkAwardArgs)
	if !ok {
		that2, ok := that.(NetworkAwardArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Award.Equal(&that1.Award) {
		return false
	}
	return true
}
func (this *AddressArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AddressArgs)
	if !ok {
		that2, ok := that.(AddressArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	return true
}
func (this *SoftwareUpgradeArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SoftwareUpgradeArgs)
	if !ok {
		that2, ok := that.(SoftwareUpgradeArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Height != that1.Height {
		return false
	}
	if this.Info != that1.Info {
		return false
	}
	if that1.Time == nil {
		if this.Time != nil {
			return false
		}
	} else if !this.Time.Equal(*that1.Time) {
		return false
	}
	return true
}
func (this *MinAmountArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MinAmountArgs)
	if !ok {
		that2, ok := that.(MinAmountArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinAmount != that1.MinAmount {
		return false
	}
	return true
}
func (this *CountArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CountArgs)
	if !ok {
		that2, ok := that.(CountArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	return true
}
func (this *StatusArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StatusArgs)
	if !ok {
		that2, ok := that.(StatusArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	return true
}
func (this *MinCriteriaArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MinCriteriaArgs)
	if !ok {
		that2, ok := that.(MinCriteriaArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinCriteria.Equal(that1.MinCriteria) {
		return false
	}
	return true
}
func (this *PeriodArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PeriodArgs)
	if !ok {
		that2, ok := that.(PeriodArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Days != that1.Days {
		return false
	}
	return true
}
func (this *PortionArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PortionArgs)
	if !ok {
		that2, ok := that.(PortionArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Fraction.Equal(that1.Fraction) {
		return false
	}
	return true
}
func (this *PortionsArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PortionsArgs)
	if !ok {
		that2, ok := that.(PortionsArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Fractions) != len(that1.Fractions) {
		return false
	}
	for i := range this.Fractions {
		if !this.Fractions[i].Equal(that1.Fractions[i]) {
			return false
		}
	}
	return true
}
func (this *AccruePercentageRangesArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AccruePercentageRangesArgs)
	if !ok {
		that2, ok := that.(AccruePercentageRangesArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AccruePercentageRanges) != len(that1.AccruePercentageRanges) {
		return false
	}
	for i := range this.AccruePercentageRanges {
		if !this.AccruePercentageRanges[i].Equal(&that1.AccruePercentageRanges[i]) {
			return false
		}
	}
	return true
}
func (this *AccruePercentageTableArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AccruePercentageTableArgs)
	if !ok {
		that2, ok := that.(AccruePercentageTableArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AccruePercentageTable) != len(that1.AccruePercentageTable) {
		return false
	}
	for i := range this.AccruePercentageTable {
		if !this.AccruePercentageTable[i].Equal(&that1.AccruePercentageTable[i]) {
			return false
		}
	}
	return true
}
func (this *RevokeArgs) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RevokeArgs)
	if !ok {
		that2, ok := that.(RevokeArgs)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Revoke.Equal(that1.Revoke) {
		return false
	}
	return true
}
func (m *PriceArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Price != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DelegationAwardArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationAwardArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationAwardArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Award.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintArgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NetworkAwardArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkAwardArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkAwardArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Award.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintArgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AddressArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintArgs(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SoftwareUpgradeArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SoftwareUpgradeArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SoftwareUpgradeArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Time):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintArgs(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Info) > 0 {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintArgs(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Height != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintArgs(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MinAmountArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinAmountArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinAmountArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinAmount != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.MinAmount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CountArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CountArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CountArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StatusArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatusArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatusArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MinCriteriaArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MinCriteriaArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MinCriteriaArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinCriteria != nil {
		{
			size, err := m.MinCriteria.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintArgs(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PeriodArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PeriodArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PeriodArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Days != 0 {
		i = encodeVarintArgs(dAtA, i, uint64(m.Days))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PortionArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PortionArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PortionArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Fraction.Size()
		i -= size
		if _, err := m.Fraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintArgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PortionsArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PortionsArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PortionsArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fractions) > 0 {
		for iNdEx := len(m.Fractions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Fractions[iNdEx].Size()
				i -= size
				if _, err := m.Fractions[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintArgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AccruePercentageRangesArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccruePercentageRangesArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccruePercentageRangesArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccruePercentageRanges) > 0 {
		for iNdEx := len(m.AccruePercentageRanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccruePercentageRanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintArgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AccruePercentageTableArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccruePercentageTableArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccruePercentageTableArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccruePercentageTable) > 0 {
		for iNdEx := len(m.AccruePercentageTable) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccruePercentageTable[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintArgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RevokeArgs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevokeArgs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevokeArgs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revoke != nil {
		{
			size, err := m.Revoke.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintArgs(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintArgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovArgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PriceArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Price != 0 {
		n += 1 + sovArgs(uint64(m.Price))
	}
	return n
}

func (m *DelegationAwardArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Award.Size()
	n += 1 + l + sovArgs(uint64(l))
	return n
}

func (m *NetworkAwardArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Award.Size()
	n += 1 + l + sovArgs(uint64(l))
	return n
}

func (m *AddressArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovArgs(uint64(l))
	}
	return n
}

func (m *SoftwareUpgradeArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovArgs(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovArgs(uint64(m.Height))
	}
	l = len(m.Info)
	if l > 0 {
		n += 1 + l + sovArgs(uint64(l))
	}
	if m.Time != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Time)
		n += 1 + l + sovArgs(uint64(l))
	}
	return n
}

func (m *MinAmountArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinAmount != 0 {
		n += 1 + sovArgs(uint64(m.MinAmount))
	}
	return n
}

func (m *CountArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovArgs(uint64(m.Count))
	}
	return n
}

func (m *StatusArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovArgs(uint64(m.Status))
	}
	return n
}

func (m *MinCriteriaArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinCriteria != nil {
		l = m.MinCriteria.Size()
		n += 1 + l + sovArgs(uint64(l))
	}
	return n
}

func (m *PeriodArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Days != 0 {
		n += 1 + sovArgs(uint64(m.Days))
	}
	return n
}

func (m *PortionArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fraction.Size()
	n += 1 + l + sovArgs(uint64(l))
	return n
}

func (m *PortionsArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fractions) > 0 {
		for _, e := range m.Fractions {
			l = e.Size()
			n += 1 + l + sovArgs(uint64(l))
		}
	}
	return n
}

func (m *AccruePercentageRangesArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AccruePercentageRanges) > 0 {
		for _, e := range m.AccruePercentageRanges {
			l = e.Size()
			n += 1 + l + sovArgs(uint64(l))
		}
	}
	return n
}

func (m *AccruePercentageTableArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AccruePercentageTable) > 0 {
		for _, e := range m.AccruePercentageTable {
			l = e.Size()
			n += 1 + l + sovArgs(uint64(l))
		}
	}
	return n
}

func (m *RevokeArgs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revoke != nil {
		l = m.Revoke.Size()
		n += 1 + l + sovArgs(uint64(l))
	}
	return n
}

func sovArgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozArgs(x uint64) (n int) {
	return sovArgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PriceArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegationAwardArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationAwardArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationAwardArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Award", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Award.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetworkAwardArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkAwardArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkAwardArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Award", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Award.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddressArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SoftwareUpgradeArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SoftwareUpgradeArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SoftwareUpgradeArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Time == nil {
				m.Time = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MinAmountArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinAmountArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinAmountArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAmount", wireType)
			}
			m.MinAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CountArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CountArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CountArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatusArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatusArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatusArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= types1.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MinCriteriaArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MinCriteriaArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MinCriteriaArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCriteria", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MinCriteria == nil {
				m.MinCriteria = &types2.MinCriteria{}
			}
			if err := m.MinCriteria.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PeriodArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeriodArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeriodArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Days", wireType)
			}
			m.Days = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Days |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PortionArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PortionArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PortionArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PortionsArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PortionsArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PortionsArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fractions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_arterynetwork_artr_util.Fraction
			m.Fractions = append(m.Fractions, v)
			if err := m.Fractions[len(m.Fractions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccruePercentageRangesArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccruePercentageRangesArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccruePercentageRangesArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruePercentageRanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccruePercentageRanges = append(m.AccruePercentageRanges, types.PercentageRange{})
			if err := m.AccruePercentageRanges[len(m.AccruePercentageRanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccruePercentageTableArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccruePercentageTableArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccruePercentageTableArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruePercentageTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccruePercentageTable = append(m.AccruePercentageTable, types.PercentageListRange{})
			if err := m.AccruePercentageTable[len(m.AccruePercentageTable)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RevokeArgs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevokeArgs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevokeArgs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoke", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revoke == nil {
				m.Revoke = &types.Revoke{}
			}
			if err := m.Revoke.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipArgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowArgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthArgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupArgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthArgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthArgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowArgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupArgs = fmt.Errorf("proto: unexpected end of group")
)
