// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: artery/voting/v1beta1/proposals.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProposalType int32

const (
	PROPOSAL_TYPE_UNSPECIFIED ProposalType = 0
	//1. Стоимость входа
	PROPOSAL_TYPE_ENTER_PRICE ProposalType = 1
	//2. Вознаграждение за делегирование
	PROPOSAL_TYPE_DELEGATION_AWARD ProposalType = 2 // Deprecated: Do not use.
	//3. Сетевое вознаграждение с делегирования
	PROPOSAL_TYPE_DELEGATION_NETWORK_AWARD ProposalType = 3 // Deprecated: Do not use.
	//4. Сетевое вознаграждение с покупки продукта
	PROPOSAL_TYPE_PRODUCT_NETWORK_AWARD ProposalType = 4 // Deprecated: Do not use.
	//5. Состав голосующего совета (включение / исключение участника)
	PROPOSAL_TYPE_GOVERNMENT_ADD ProposalType = 5
	//5. Состав голосующего совета (включение / исключение участника)
	PROPOSAL_TYPE_GOVERNMENT_REMOVE ProposalType = 6
	//6. Стоимость VPN / гб сверх тарифа
	PROPOSAL_TYPE_PRODUCT_VPN_BASE_PRICE ProposalType = 7
	//7. Стоимость storage / гб сверх тарифа
	PROPOSAL_TYPE_PRODUCT_STORAGE_BASE_PRICE ProposalType = 8
	// Аккаунт с правом бесплатного создания новых аккаунтов
	PROPOSAL_TYPE_FREE_CREATOR_ADD ProposalType = 9
	// Аккаунт с правом бесплатного создания новых аккаунтов
	PROPOSAL_TYPE_FREE_CREATOR_REMOVE ProposalType = 10
	// Обновление blockchain
	PROPOSAL_TYPE_SOFTWARE_UPGRADE ProposalType = 11
	// Обновление blockchain
	PROPOSAL_TYPE_CANCEL_SOFTWARE_UPGRADE ProposalType = 12
	// Служебные (с иммунитетом к изменению статуса и делегации) валидаторы
	PROPOSAL_TYPE_STAFF_VALIDATOR_ADD ProposalType = 13
	// Служебные (с иммунитетом к изменению статуса и делегации) валидаторы
	PROPOSAL_TYPE_STAFF_VALIDATOR_REMOVE ProposalType = 14
	// Кто может подписывать транзакции на выплату вознаграждений за хранилище/VPN
	PROPOSAL_TYPE_EARNING_SIGNER_ADD ProposalType = 15
	// Кто может подписывать транзакции на выплату вознаграждений за хранилище/VPN
	PROPOSAL_TYPE_EARNING_SIGNER_REMOVE ProposalType = 16
	// Кто может менять курс монетки
	PROPOSAL_TYPE_TOKEN_RATE_SIGNER_ADD ProposalType = 17
	// Кто может менять курс монетки
	PROPOSAL_TYPE_TOKEN_RATE_SIGNER_REMOVE ProposalType = 18
	// Кто считает трафик VPN и актуализирует данные по нему
	PROPOSAL_TYPE_VPN_SIGNER_ADD ProposalType = 19
	// Кто считает трафик VPN и актуализирует данные по нему
	PROPOSAL_TYPE_VPN_SIGNER_REMOVE ProposalType = 20
	// Кто считает занятое место и актуализирует данные по нему
	PROPOSAL_TYPE_STORAGE_SIGNER_ADD ProposalType = 21
	// Кто считает занятое место и актуализирует данные по нему
	PROPOSAL_TYPE_STORAGE_SIGNER_REMOVE ProposalType = 22
	// Стоимость переноса аккаунта к другому пригласившему
	PROPOSAL_TYPE_TRANSITION_PRICE ProposalType = 23
	// Минимальная сумма перевода
	PROPOSAL_TYPE_MIN_SEND ProposalType = 24
	// Минимальная сумма делегирования
	PROPOSAL_TYPE_MIN_DELEGATE ProposalType = 25
	// Максимальное количество валидаторов
	PROPOSAL_TYPE_MAX_VALIDATORS ProposalType = 26
	// "Счастливые" валидаторы
	PROPOSAL_TYPE_LUCKY_VALIDATORS ProposalType = 27
	// Амнистия
	PROPOSAL_TYPE_GENERAL_AMNESTY ProposalType = 28
	// Статус, начиная с которого доступна валидация
	PROPOSAL_TYPE_VALIDATOR_MINIMAL_STATUS ProposalType = 29 // Deprecated: Do not use.
	// Критерии, после удовлетворения которым доступна валидация
	PROPOSAL_TYPE_VALIDATOR_MINIMAL_CRITERIA ProposalType = 47
	// Количество блоков, которое надо пропустить чтобы заработать jail
	PROPOSAL_TYPE_JAIL_AFTER ProposalType = 30
	// Через сколько дней монеты вернутся с делегирования
	PROPOSAL_TYPE_REVOKE_PERIOD ProposalType = 31 // Deprecated: Do not use.
	// Делегирование РАВНОЕ или меньше этой суммы считается принебрежимо малым
	PROPOSAL_TYPE_DUST_DELEGATION ProposalType = 32
	// Разбивка voting power по процентилям
	PROPOSAL_TYPE_VOTING_POWER ProposalType = 33
	// PROPOSAL_TYPE_VALIDATOR_BONUS - Дополнительный процент с делегирования, который получают активные валидаторы
	PROPOSAL_TYPE_VALIDATOR_BONUS ProposalType = 34 // Deprecated: Do not use.
	// PROPOSAL_TYPE_SUBSCRIPTION_BONUS - Дополнительный процент с делегирования, который получают пользователи с активной подпиской
	PROPOSAL_TYPE_SUBSCRIPTION_BONUS ProposalType = 43 // Deprecated: Do not use.
	// PROPOSAL_TYPE_VPN_BONUS - Дополнительный процент с делегирования, который получают пользователи с активной vpn нодой
	PROPOSAL_TYPE_VPN_BONUS ProposalType = 44 // Deprecated: Do not use.
	// PROPOSAL_TYPE_STORAGE_BONUS - Дополнительный процент с делегирования, который получают пользователи с активной storage нодой
	PROPOSAL_TYPE_STORAGE_BONUS ProposalType = 45 // Deprecated: Do not use.
	// PROPOSAL_TYPE_VALIDATOR - Процент с делегирования, который получают активные валидаторы
	PROPOSAL_TYPE_VALIDATOR ProposalType = 35 // Deprecated: Do not use.
	// Комиссия за перевод
	PROPOSAL_TYPE_TRANSACTION_FEE ProposalType = 36
	// Процент сжигаемый при разделегировании
	PROPOSAL_TYPE_BURN_ON_REVOKE ProposalType = 37 // Deprecated: Do not use.
	// Максимальная комиссия за перевод
	PROPOSAL_TYPE_MAX_TRANSACTION_FEE ProposalType = 38
	// Пропорции в которых делится комиссия за перевод между пропозером, компанией и сжиганием
	PROPOSAL_TYPE_TRANSACTION_FEE_SPLIT_RATIOS ProposalType = 39
	// Вознаграждение за делегирование с возможностью указать произвольные диапазоны
	PROPOSAL_TYPE_ACCRUE_PERCENTAGE_RANGES ProposalType = 40 // Deprecated: Do not use.
	// Вознаграждение за делегирование с возможностью указать произвольные диапазоны для пяти категорий: базовое, бонус валидатора, бонус за подписку, бонус за vpn ноду, бонус за storage ноду
	PROPOSAL_TYPE_ACCRUE_PERCENTAGE_TABLE ProposalType = 46
	// Адреса с которых заблокированна отправка токенов (включение / исключение участника)
	PROPOSAL_TYPE_BLOCKED_SENDER_ADD ProposalType = 41
	// Адреса с которых заблокированна отправка токенов (включение / исключение участника)
	PROPOSAL_TYPE_BLOCKED_SENDER_REMOVE ProposalType = 42
	// Параметры обычного разделегирования: через сколько дней монеты вернутся с делегирования и процент сжигаемый при разделегировании
	PROPOSAL_TYPE_REVOKE ProposalType = 48
	// Параметры срочного разделегирования: через сколько дней монеты вернутся с делегирования и процент сжигаемый при разделегировании
	PROPOSAL_TYPE_EXPRESS_REVOKE ProposalType = 49
)

var ProposalType_name = map[int32]string{
	0:  "PROPOSAL_TYPE_UNSPECIFIED",
	1:  "PROPOSAL_TYPE_ENTER_PRICE",
	2:  "PROPOSAL_TYPE_DELEGATION_AWARD",
	3:  "PROPOSAL_TYPE_DELEGATION_NETWORK_AWARD",
	4:  "PROPOSAL_TYPE_PRODUCT_NETWORK_AWARD",
	5:  "PROPOSAL_TYPE_GOVERNMENT_ADD",
	6:  "PROPOSAL_TYPE_GOVERNMENT_REMOVE",
	7:  "PROPOSAL_TYPE_PRODUCT_VPN_BASE_PRICE",
	8:  "PROPOSAL_TYPE_PRODUCT_STORAGE_BASE_PRICE",
	9:  "PROPOSAL_TYPE_FREE_CREATOR_ADD",
	10: "PROPOSAL_TYPE_FREE_CREATOR_REMOVE",
	11: "PROPOSAL_TYPE_SOFTWARE_UPGRADE",
	12: "PROPOSAL_TYPE_CANCEL_SOFTWARE_UPGRADE",
	13: "PROPOSAL_TYPE_STAFF_VALIDATOR_ADD",
	14: "PROPOSAL_TYPE_STAFF_VALIDATOR_REMOVE",
	15: "PROPOSAL_TYPE_EARNING_SIGNER_ADD",
	16: "PROPOSAL_TYPE_EARNING_SIGNER_REMOVE",
	17: "PROPOSAL_TYPE_TOKEN_RATE_SIGNER_ADD",
	18: "PROPOSAL_TYPE_TOKEN_RATE_SIGNER_REMOVE",
	19: "PROPOSAL_TYPE_VPN_SIGNER_ADD",
	20: "PROPOSAL_TYPE_VPN_SIGNER_REMOVE",
	21: "PROPOSAL_TYPE_STORAGE_SIGNER_ADD",
	22: "PROPOSAL_TYPE_STORAGE_SIGNER_REMOVE",
	23: "PROPOSAL_TYPE_TRANSITION_PRICE",
	24: "PROPOSAL_TYPE_MIN_SEND",
	25: "PROPOSAL_TYPE_MIN_DELEGATE",
	26: "PROPOSAL_TYPE_MAX_VALIDATORS",
	27: "PROPOSAL_TYPE_LUCKY_VALIDATORS",
	28: "PROPOSAL_TYPE_GENERAL_AMNESTY",
	29: "PROPOSAL_TYPE_VALIDATOR_MINIMAL_STATUS",
	47: "PROPOSAL_TYPE_VALIDATOR_MINIMAL_CRITERIA",
	30: "PROPOSAL_TYPE_JAIL_AFTER",
	31: "PROPOSAL_TYPE_REVOKE_PERIOD",
	32: "PROPOSAL_TYPE_DUST_DELEGATION",
	33: "PROPOSAL_TYPE_VOTING_POWER",
	34: "PROPOSAL_TYPE_VALIDATOR_BONUS",
	43: "PROPOSAL_TYPE_SUBSCRIPTION_BONUS",
	44: "PROPOSAL_TYPE_VPN_BONUS",
	45: "PROPOSAL_TYPE_STORAGE_BONUS",
	35: "PROPOSAL_TYPE_VALIDATOR",
	36: "PROPOSAL_TYPE_TRANSACTION_FEE",
	37: "PROPOSAL_TYPE_BURN_ON_REVOKE",
	38: "PROPOSAL_TYPE_MAX_TRANSACTION_FEE",
	39: "PROPOSAL_TYPE_TRANSACTION_FEE_SPLIT_RATIOS",
	40: "PROPOSAL_TYPE_ACCRUE_PERCENTAGE_RANGES",
	46: "PROPOSAL_TYPE_ACCRUE_PERCENTAGE_TABLE",
	41: "PROPOSAL_TYPE_BLOCKED_SENDER_ADD",
	42: "PROPOSAL_TYPE_BLOCKED_SENDER_REMOVE",
	48: "PROPOSAL_TYPE_REVOKE",
	49: "PROPOSAL_TYPE_EXPRESS_REVOKE",
}

var ProposalType_value = map[string]int32{
	"PROPOSAL_TYPE_UNSPECIFIED":                  0,
	"PROPOSAL_TYPE_ENTER_PRICE":                  1,
	"PROPOSAL_TYPE_DELEGATION_AWARD":             2,
	"PROPOSAL_TYPE_DELEGATION_NETWORK_AWARD":     3,
	"PROPOSAL_TYPE_PRODUCT_NETWORK_AWARD":        4,
	"PROPOSAL_TYPE_GOVERNMENT_ADD":               5,
	"PROPOSAL_TYPE_GOVERNMENT_REMOVE":            6,
	"PROPOSAL_TYPE_PRODUCT_VPN_BASE_PRICE":       7,
	"PROPOSAL_TYPE_PRODUCT_STORAGE_BASE_PRICE":   8,
	"PROPOSAL_TYPE_FREE_CREATOR_ADD":             9,
	"PROPOSAL_TYPE_FREE_CREATOR_REMOVE":          10,
	"PROPOSAL_TYPE_SOFTWARE_UPGRADE":             11,
	"PROPOSAL_TYPE_CANCEL_SOFTWARE_UPGRADE":      12,
	"PROPOSAL_TYPE_STAFF_VALIDATOR_ADD":          13,
	"PROPOSAL_TYPE_STAFF_VALIDATOR_REMOVE":       14,
	"PROPOSAL_TYPE_EARNING_SIGNER_ADD":           15,
	"PROPOSAL_TYPE_EARNING_SIGNER_REMOVE":        16,
	"PROPOSAL_TYPE_TOKEN_RATE_SIGNER_ADD":        17,
	"PROPOSAL_TYPE_TOKEN_RATE_SIGNER_REMOVE":     18,
	"PROPOSAL_TYPE_VPN_SIGNER_ADD":               19,
	"PROPOSAL_TYPE_VPN_SIGNER_REMOVE":            20,
	"PROPOSAL_TYPE_STORAGE_SIGNER_ADD":           21,
	"PROPOSAL_TYPE_STORAGE_SIGNER_REMOVE":        22,
	"PROPOSAL_TYPE_TRANSITION_PRICE":             23,
	"PROPOSAL_TYPE_MIN_SEND":                     24,
	"PROPOSAL_TYPE_MIN_DELEGATE":                 25,
	"PROPOSAL_TYPE_MAX_VALIDATORS":               26,
	"PROPOSAL_TYPE_LUCKY_VALIDATORS":             27,
	"PROPOSAL_TYPE_GENERAL_AMNESTY":              28,
	"PROPOSAL_TYPE_VALIDATOR_MINIMAL_STATUS":     29,
	"PROPOSAL_TYPE_VALIDATOR_MINIMAL_CRITERIA":   47,
	"PROPOSAL_TYPE_JAIL_AFTER":                   30,
	"PROPOSAL_TYPE_REVOKE_PERIOD":                31,
	"PROPOSAL_TYPE_DUST_DELEGATION":              32,
	"PROPOSAL_TYPE_VOTING_POWER":                 33,
	"PROPOSAL_TYPE_VALIDATOR_BONUS":              34,
	"PROPOSAL_TYPE_SUBSCRIPTION_BONUS":           43,
	"PROPOSAL_TYPE_VPN_BONUS":                    44,
	"PROPOSAL_TYPE_STORAGE_BONUS":                45,
	"PROPOSAL_TYPE_VALIDATOR":                    35,
	"PROPOSAL_TYPE_TRANSACTION_FEE":              36,
	"PROPOSAL_TYPE_BURN_ON_REVOKE":               37,
	"PROPOSAL_TYPE_MAX_TRANSACTION_FEE":          38,
	"PROPOSAL_TYPE_TRANSACTION_FEE_SPLIT_RATIOS": 39,
	"PROPOSAL_TYPE_ACCRUE_PERCENTAGE_RANGES":     40,
	"PROPOSAL_TYPE_ACCRUE_PERCENTAGE_TABLE":      46,
	"PROPOSAL_TYPE_BLOCKED_SENDER_ADD":           41,
	"PROPOSAL_TYPE_BLOCKED_SENDER_REMOVE":        42,
	"PROPOSAL_TYPE_REVOKE":                       48,
	"PROPOSAL_TYPE_EXPRESS_REVOKE":               49,
}

func (x ProposalType) String() string {
	return proto.EnumName(ProposalType_name, int32(x))
}

func (ProposalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3222b1bdae673c73, []int{0}
}

func init() {
	proto.RegisterEnum("artery.voting.v1beta1.ProposalType", ProposalType_name, ProposalType_value)
}

func init() {
	proto.RegisterFile("artery/voting/v1beta1/proposals.proto", fileDescriptor_3222b1bdae673c73)
}

var fileDescriptor_3222b1bdae673c73 = []byte{
	// 821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x96, 0xd1, 0x72, 0x1b, 0x35,
	0x14, 0x86, 0xed, 0x52, 0x4a, 0x11, 0x85, 0x0a, 0x91, 0xb6, 0xa9, 0x9b, 0x6c, 0x92, 0xda, 0x4e,
	0x5d, 0x37, 0xd8, 0x64, 0x78, 0x02, 0x79, 0xf7, 0xac, 0x47, 0x78, 0x2d, 0xed, 0x48, 0x5a, 0xbb,
	0xe1, 0x46, 0x93, 0x30, 0x1e, 0xd3, 0x01, 0xba, 0x1e, 0xc7, 0x14, 0xf2, 0x02, 0x0c, 0x97, 0xbc,
	0x03, 0x2f, 0xc3, 0x65, 0x2f, 0xb9, 0x64, 0x92, 0x17, 0x61, 0x56, 0xbb, 0x6e, 0xec, 0x95, 0x93,
	0xbb, 0x64, 0xf4, 0xcd, 0x7f, 0xce, 0xd1, 0xf9, 0x7f, 0xad, 0x51, 0xf3, 0x74, 0xbe, 0x98, 0xcc,
	0x2f, 0xba, 0xef, 0xd2, 0xc5, 0x9b, 0xb7, 0xd3, 0xee, 0xbb, 0xe3, 0xb3, 0xc9, 0xe2, 0xf4, 0xb8,
	0x3b, 0x9b, 0xa7, 0xb3, 0xf4, 0xfc, 0xf4, 0xe7, 0xf3, 0xce, 0x6c, 0x9e, 0x2e, 0x52, 0xf2, 0x28,
	0xc7, 0x3a, 0x39, 0xd6, 0x29, 0xb0, 0xda, 0xd6, 0x34, 0x9d, 0xa6, 0x96, 0xe8, 0x66, 0x7f, 0xe5,
	0x70, 0xfb, 0x8f, 0x87, 0xe8, 0x41, 0x5c, 0x08, 0xe8, 0x8b, 0xd9, 0x84, 0xec, 0xa2, 0xa7, 0xb1,
	0x14, 0xb1, 0x50, 0x34, 0x32, 0xfa, 0x24, 0x06, 0x93, 0x70, 0x15, 0x83, 0xcf, 0x42, 0x06, 0x01,
	0xae, 0xb8, 0xc7, 0xc0, 0x35, 0x48, 0x13, 0x4b, 0xe6, 0x03, 0xae, 0x92, 0x43, 0xe4, 0xad, 0x1f,
	0x07, 0x10, 0x41, 0x9f, 0x6a, 0x26, 0xb8, 0xa1, 0x63, 0x2a, 0x03, 0x7c, 0xa7, 0x76, 0xe7, 0x7e,
	0x95, 0x74, 0xd0, 0xe1, 0x8d, 0x1c, 0x07, 0x3d, 0x16, 0x72, 0x50, 0xf0, 0x1f, 0x59, 0xfe, 0x15,
	0xaa, 0xaf, 0xf3, 0xb1, 0x14, 0x41, 0xe2, 0xeb, 0x12, 0x7c, 0xd7, 0xc2, 0xfb, 0x68, 0x67, 0x1d,
	0xee, 0x8b, 0x11, 0x48, 0x3e, 0x04, 0xae, 0x0d, 0x0d, 0x02, 0xfc, 0x31, 0xa9, 0xa3, 0xbd, 0x1b,
	0x09, 0x09, 0x43, 0x31, 0x02, 0x7c, 0x8f, 0xb4, 0x50, 0x63, 0x73, 0xcd, 0x51, 0xcc, 0x4d, 0x8f,
	0x2a, 0x28, 0xa6, 0xfe, 0x84, 0x1c, 0xa1, 0xd6, 0x66, 0x52, 0x69, 0x21, 0x69, 0x1f, 0x56, 0xe9,
	0xfb, 0xe4, 0x79, 0xf9, 0x8e, 0x42, 0x09, 0x60, 0x7c, 0x09, 0x54, 0x0b, 0x69, 0x1b, 0xfc, 0x94,
	0x34, 0xd1, 0xc1, 0x2d, 0x4c, 0xd1, 0x22, 0x72, 0xa5, 0x94, 0x08, 0xf5, 0x98, 0x4a, 0x30, 0x49,
	0xdc, 0x97, 0x34, 0x00, 0xfc, 0x19, 0x79, 0x89, 0x9a, 0xeb, 0x8c, 0x4f, 0xb9, 0x0f, 0x91, 0x8b,
	0x3e, 0x70, 0xab, 0x2a, 0x4d, 0xc3, 0xd0, 0x8c, 0x68, 0xc4, 0x82, 0x0f, 0xcd, 0x7d, 0xee, 0x5e,
	0x4c, 0x19, 0x2b, 0xfa, 0xfb, 0x82, 0x34, 0xd0, 0x7e, 0xc9, 0x2d, 0x54, 0x72, 0xc6, 0xfb, 0x46,
	0xb1, 0x3e, 0x87, 0x5c, 0xef, 0x21, 0x79, 0x51, 0x5e, 0x6e, 0x89, 0x2a, 0xe4, 0xb0, 0x0b, 0x6a,
	0x31, 0x00, 0x6e, 0x24, 0xd5, 0xb0, 0xaa, 0xf8, 0x25, 0x69, 0x97, 0xed, 0xe5, 0x82, 0x85, 0x28,
	0x71, 0xdd, 0x92, 0xad, 0x77, 0x45, 0xed, 0x2b, 0xd7, 0x2d, 0x2b, 0x44, 0x21, 0xb3, 0xe5, 0x8e,
	0xba, 0xdc, 0xfd, 0x8a, 0xd4, 0x23, 0x77, 0x82, 0x12, 0x55, 0xc8, 0x3d, 0x76, 0x37, 0xab, 0x25,
	0xe5, 0x8a, 0xd9, 0x80, 0xe4, 0x46, 0x7a, 0x42, 0x6a, 0xe8, 0xf1, 0x3a, 0x33, 0x64, 0xdc, 0x28,
	0xe0, 0x01, 0xde, 0x26, 0x1e, 0xaa, 0xb9, 0x67, 0x45, 0xc8, 0x00, 0x3f, 0x75, 0xa7, 0x1e, 0xd2,
	0xd7, 0xd7, 0x1b, 0x54, 0xb8, 0xe6, 0x76, 0x10, 0x25, 0xfe, 0xe0, 0x64, 0x95, 0x79, 0x46, 0x0e,
	0xd0, 0x6e, 0x29, 0x47, 0xc0, 0x41, 0xd2, 0xc8, 0xd0, 0x21, 0x07, 0xa5, 0x4f, 0xf0, 0x8e, 0x9b,
	0xf4, 0x6b, 0x9b, 0x0c, 0x19, 0x67, 0x43, 0x1a, 0x65, 0xf6, 0xd1, 0x89, 0xc2, 0xbb, 0x36, 0xbc,
	0x4e, 0x96, 0x5c, 0xde, 0x97, 0x4c, 0x83, 0x64, 0x14, 0x77, 0xc9, 0x0e, 0xda, 0x5e, 0xa7, 0xbf,
	0xa3, 0x2c, 0x32, 0x34, 0xd4, 0x20, 0xb1, 0x47, 0xea, 0xe8, 0xd9, 0xfa, 0xa9, 0x84, 0x91, 0x18,
	0x80, 0x89, 0x41, 0x32, 0x11, 0xe0, 0x3d, 0x5b, 0xd0, 0x99, 0x21, 0x48, 0x94, 0x5e, 0x79, 0x8f,
	0xf0, 0xbe, 0x7b, 0x99, 0x23, 0xa1, 0x33, 0x7f, 0xc6, 0x62, 0x0c, 0x12, 0x1f, 0x90, 0x66, 0x59,
	0xe2, 0xba, 0xe7, 0x9e, 0xe0, 0x89, 0xc2, 0xcf, 0x6d, 0xa5, 0x96, 0x63, 0x91, 0xa4, 0xa7, 0x7c,
	0xc9, 0x62, 0xbb, 0xd5, 0x9c, 0x7c, 0x65, 0xc9, 0x3d, 0xf4, 0xc4, 0x75, 0x5c, 0x0e, 0x1c, 0x59,
	0xc0, 0x99, 0xec, 0xc3, 0x4b, 0x63, 0xa1, 0xaf, 0x6f, 0x50, 0x59, 0xb6, 0x85, 0xeb, 0x9b, 0x47,
	0xb7, 0x26, 0xa3, 0xbe, 0xed, 0x27, 0x04, 0xc0, 0x0d, 0xd2, 0x28, 0xfb, 0xa4, 0x97, 0x48, 0x6e,
	0x04, 0x2f, 0xae, 0x12, 0x37, 0xad, 0x90, 0xf3, 0x70, 0x64, 0x6e, 0x2a, 0x8b, 0x1d, 0x92, 0x0e,
	0x6a, 0xdf, 0x5a, 0xcf, 0xa8, 0x38, 0x62, 0x3a, 0x8b, 0x29, 0x13, 0x0a, 0xbf, 0x70, 0xbd, 0x43,
	0x7d, 0x5f, 0x26, 0x76, 0x7f, 0x3e, 0x70, 0x9d, 0xcd, 0x2b, 0x29, 0xef, 0x83, 0xc2, 0x2d, 0xdb,
	0x86, 0xf3, 0xd4, 0xb9, 0xbc, 0xa6, 0xbd, 0x08, 0x70, 0xc7, 0x8d, 0x6b, 0x2f, 0x12, 0xfe, 0x00,
	0x02, 0x9b, 0x9f, 0x22, 0xae, 0x2f, 0xdd, 0xb8, 0x96, 0xa8, 0x22, 0xae, 0x6d, 0xb2, 0x8d, 0xb6,
	0x36, 0x39, 0x0d, 0x7f, 0xe3, 0x06, 0x0d, 0x5e, 0xc7, 0x12, 0x94, 0x5a, 0x12, 0xc7, 0xb5, 0xbb,
	0x7f, 0xfe, 0xed, 0x55, 0x7a, 0xe1, 0x3f, 0x97, 0x5e, 0xf5, 0xfd, 0xa5, 0x57, 0xfd, 0xef, 0xd2,
	0xab, 0xfe, 0x75, 0xe5, 0x55, 0xde, 0x5f, 0x79, 0x95, 0x7f, 0xaf, 0xbc, 0xca, 0xf7, 0x47, 0xd3,
	0x37, 0x8b, 0x1f, 0x7f, 0x3d, 0xeb, 0xfc, 0x90, 0xfe, 0xd2, 0xcd, 0x3f, 0xed, 0x6f, 0x27, 0x8b,
	0xdf, 0xd2, 0xf9, 0x4f, 0xd9, 0x7f, 0xf3, 0xee, 0xef, 0xcb, 0xdf, 0x03, 0x8b, 0x8b, 0xd9, 0xe4,
	0xfc, 0xec, 0x9e, 0xfd, 0xae, 0x7f, 0xfb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x71, 0x81,
	0xca, 0x2d, 0x08, 0x00, 0x00,
}
