// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: artery/voting/v1beta1/types.proto

package types

import (
	fmt "fmt"
	github_com_arterynetwork_artr_util "github.com/arterynetwork/artr/util"
	types "github.com/arterynetwork/artr/x/noding/types"
	types1 "github.com/arterynetwork/artr/x/referral/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Decision int32

const (
	DECISION_UNSPECIFIED Decision = 0
	DECISION_POSITIVE    Decision = 1
	DECISION_NEGATIVE    Decision = 2
)

var Decision_name = map[int32]string{
	0: "DECISION_UNSPECIFIED",
	1: "DECISION_POSITIVE",
	2: "DECISION_NEGATIVE",
}

var Decision_value = map[string]int32{
	"DECISION_UNSPECIFIED": 0,
	"DECISION_POSITIVE":    1,
	"DECISION_NEGATIVE":    2,
}

func (x Decision) String() string {
	return proto.EnumName(Decision_name, int32(x))
}

func (Decision) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{0}
}

type Proposal struct {
	Name     string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty"`
	Author   string       `protobuf:"bytes,2,opt,name=author,proto3" json:"author" yaml:"author"`
	Type     ProposalType `protobuf:"varint,3,opt,name=type,proto3,enum=artery.voting.v1beta1.ProposalType" json:"type" yaml:"type"`
	EndBlock uint64       `protobuf:"varint,16,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	EndTime  *time.Time   `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time,omitempty"`
	// Types that are valid to be assigned to Args:
	//	*Proposal_Price
	//	*Proposal_DelegationAward
	//	*Proposal_NetworkAward
	//	*Proposal_Address
	//	*Proposal_SoftwareUpgrade
	//	*Proposal_MinAmount
	//	*Proposal_Count
	//	*Proposal_Status
	//	*Proposal_MinCriteria
	//	*Proposal_Period
	//	*Proposal_VotingPower
	//	*Proposal_Portion
	//	*Proposal_Portions
	//	*Proposal_AccruePercentageRanges
	//	*Proposal_AccruePercentageTable
	//	*Proposal_Revoke
	Args isProposal_Args `protobuf_oneof:"args"`
}

func (m *Proposal) Reset()      { *m = Proposal{} }
func (*Proposal) ProtoMessage() {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{0}
}
func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return m.Size()
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

type isProposal_Args interface {
	isProposal_Args()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type Proposal_Price struct {
	Price *PriceArgs `protobuf:"bytes,5,opt,name=price,proto3,oneof" json:"price,omitempty" yaml:"price,omitempty`
}
type Proposal_DelegationAward struct {
	DelegationAward *DelegationAwardArgs `protobuf:"bytes,6,opt,name=delegation_award,json=delegationAward,proto3,oneof" json:"delegation_award,omitempty" yaml:"delegation_award,omitempty`
}
type Proposal_NetworkAward struct {
	NetworkAward *NetworkAwardArgs `protobuf:"bytes,7,opt,name=network_award,json=networkAward,proto3,oneof" json:"network_award,omitempty" yaml:"network_award,omitempty`
}
type Proposal_Address struct {
	Address *AddressArgs `protobuf:"bytes,8,opt,name=address,proto3,oneof" json:"address,omitempty" yaml:"address,omitempty`
}
type Proposal_SoftwareUpgrade struct {
	SoftwareUpgrade *SoftwareUpgradeArgs `protobuf:"bytes,9,opt,name=software_upgrade,json=softwareUpgrade,proto3,oneof" json:"software_upgrade,omitempty" yaml:"software_upgrade,omitempty`
}
type Proposal_MinAmount struct {
	MinAmount *MinAmountArgs `protobuf:"bytes,10,opt,name=min_amount,json=minAmount,proto3,oneof" json:"min_amount,omitempty" yaml:"min_amount,omitempty`
}
type Proposal_Count struct {
	Count *CountArgs `protobuf:"bytes,11,opt,name=count,proto3,oneof" json:"count,omitempty" yaml:"count,omitempty`
}
type Proposal_Status struct {
	Status *StatusArgs `protobuf:"bytes,12,opt,name=status,proto3,oneof" json:"status,omitempty" yaml:"status,omitempty`
}
type Proposal_MinCriteria struct {
	MinCriteria *MinCriteriaArgs `protobuf:"bytes,20,opt,name=min_criteria,json=minCriteria,proto3,oneof" json:"min_criteria,omitempty"`
}
type Proposal_Period struct {
	Period *PeriodArgs `protobuf:"bytes,13,opt,name=period,proto3,oneof" json:"period,omitempty" yaml:"period,omitempty`
}
type Proposal_VotingPower struct {
	VotingPower *types.Distribution `protobuf:"bytes,14,opt,name=votingPower,proto3,oneof" json:"voting_power,omitempty" yaml:"voting_power,omitempty`
}
type Proposal_Portion struct {
	Portion *PortionArgs `protobuf:"bytes,15,opt,name=portion,proto3,oneof" json:"portion,omitempty" yaml:"portion,omitempty`
}
type Proposal_Portions struct {
	Portions *PortionsArgs `protobuf:"bytes,17,opt,name=portions,proto3,oneof" json:"portions,omitempty" yaml:"portions,omitempty`
}
type Proposal_AccruePercentageRanges struct {
	AccruePercentageRanges *AccruePercentageRangesArgs `protobuf:"bytes,18,opt,name=accrue_percentage_ranges,json=accruePercentageRanges,proto3,oneof" json:"accrue_percentage_ranges,omitempty"`
}
type Proposal_AccruePercentageTable struct {
	AccruePercentageTable *AccruePercentageTableArgs `protobuf:"bytes,19,opt,name=accrue_percentage_table,json=accruePercentageTable,proto3,oneof" json:"accrue_percentage_table,omitempty"`
}
type Proposal_Revoke struct {
	Revoke *RevokeArgs `protobuf:"bytes,21,opt,name=revoke,proto3,oneof" json:"revoke,omitempty"`
}

func (*Proposal_Price) isProposal_Args()                  {}
func (*Proposal_DelegationAward) isProposal_Args()        {}
func (*Proposal_NetworkAward) isProposal_Args()           {}
func (*Proposal_Address) isProposal_Args()                {}
func (*Proposal_SoftwareUpgrade) isProposal_Args()        {}
func (*Proposal_MinAmount) isProposal_Args()              {}
func (*Proposal_Count) isProposal_Args()                  {}
func (*Proposal_Status) isProposal_Args()                 {}
func (*Proposal_MinCriteria) isProposal_Args()            {}
func (*Proposal_Period) isProposal_Args()                 {}
func (*Proposal_VotingPower) isProposal_Args()            {}
func (*Proposal_Portion) isProposal_Args()                {}
func (*Proposal_Portions) isProposal_Args()               {}
func (*Proposal_AccruePercentageRanges) isProposal_Args() {}
func (*Proposal_AccruePercentageTable) isProposal_Args()  {}
func (*Proposal_Revoke) isProposal_Args()                 {}

func (m *Proposal) GetArgs() isProposal_Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Proposal) GetPrice() *PriceArgs {
	if x, ok := m.GetArgs().(*Proposal_Price); ok {
		return x.Price
	}
	return nil
}

// Deprecated: Do not use.
func (m *Proposal) GetDelegationAward() *DelegationAwardArgs {
	if x, ok := m.GetArgs().(*Proposal_DelegationAward); ok {
		return x.DelegationAward
	}
	return nil
}

// Deprecated: Do not use.
func (m *Proposal) GetNetworkAward() *NetworkAwardArgs {
	if x, ok := m.GetArgs().(*Proposal_NetworkAward); ok {
		return x.NetworkAward
	}
	return nil
}

func (m *Proposal) GetAddress() *AddressArgs {
	if x, ok := m.GetArgs().(*Proposal_Address); ok {
		return x.Address
	}
	return nil
}

func (m *Proposal) GetSoftwareUpgrade() *SoftwareUpgradeArgs {
	if x, ok := m.GetArgs().(*Proposal_SoftwareUpgrade); ok {
		return x.SoftwareUpgrade
	}
	return nil
}

func (m *Proposal) GetMinAmount() *MinAmountArgs {
	if x, ok := m.GetArgs().(*Proposal_MinAmount); ok {
		return x.MinAmount
	}
	return nil
}

func (m *Proposal) GetCount() *CountArgs {
	if x, ok := m.GetArgs().(*Proposal_Count); ok {
		return x.Count
	}
	return nil
}

// Deprecated: Do not use.
func (m *Proposal) GetStatus() *StatusArgs {
	if x, ok := m.GetArgs().(*Proposal_Status); ok {
		return x.Status
	}
	return nil
}

func (m *Proposal) GetMinCriteria() *MinCriteriaArgs {
	if x, ok := m.GetArgs().(*Proposal_MinCriteria); ok {
		return x.MinCriteria
	}
	return nil
}

// Deprecated: Do not use.
func (m *Proposal) GetPeriod() *PeriodArgs {
	if x, ok := m.GetArgs().(*Proposal_Period); ok {
		return x.Period
	}
	return nil
}

func (m *Proposal) GetVotingPower() *types.Distribution {
	if x, ok := m.GetArgs().(*Proposal_VotingPower); ok {
		return x.VotingPower
	}
	return nil
}

func (m *Proposal) GetPortion() *PortionArgs {
	if x, ok := m.GetArgs().(*Proposal_Portion); ok {
		return x.Portion
	}
	return nil
}

func (m *Proposal) GetPortions() *PortionsArgs {
	if x, ok := m.GetArgs().(*Proposal_Portions); ok {
		return x.Portions
	}
	return nil
}

// Deprecated: Do not use.
func (m *Proposal) GetAccruePercentageRanges() *AccruePercentageRangesArgs {
	if x, ok := m.GetArgs().(*Proposal_AccruePercentageRanges); ok {
		return x.AccruePercentageRanges
	}
	return nil
}

func (m *Proposal) GetAccruePercentageTable() *AccruePercentageTableArgs {
	if x, ok := m.GetArgs().(*Proposal_AccruePercentageTable); ok {
		return x.AccruePercentageTable
	}
	return nil
}

func (m *Proposal) GetRevoke() *RevokeArgs {
	if x, ok := m.GetArgs().(*Proposal_Revoke); ok {
		return x.Revoke
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Proposal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Proposal_Price)(nil),
		(*Proposal_DelegationAward)(nil),
		(*Proposal_NetworkAward)(nil),
		(*Proposal_Address)(nil),
		(*Proposal_SoftwareUpgrade)(nil),
		(*Proposal_MinAmount)(nil),
		(*Proposal_Count)(nil),
		(*Proposal_Status)(nil),
		(*Proposal_MinCriteria)(nil),
		(*Proposal_Period)(nil),
		(*Proposal_VotingPower)(nil),
		(*Proposal_Portion)(nil),
		(*Proposal_Portions)(nil),
		(*Proposal_AccruePercentageRanges)(nil),
		(*Proposal_AccruePercentageTable)(nil),
		(*Proposal_Revoke)(nil),
	}
}

type ProposalHistoryRecord struct {
	Proposal   Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal" yaml:"proposal"`
	Government []string `protobuf:"bytes,2,rep,name=government,proto3" json:"government,omitempty" yaml:"government,omitempty"`
	Agreed     []string `protobuf:"bytes,3,rep,name=agreed,proto3" json:"agreed,omitempty" yaml:"agreed,omitempty"`
	Disagreed  []string `protobuf:"bytes,4,rep,name=disagreed,proto3" json:"disagreed,omitempty" yaml:"disagreed,omitempty"`
	Started    int64    `protobuf:"varint,5,opt,name=started,proto3" json:"started,omitempty" yaml:"started,omitempty"`
	Finished   int64    `protobuf:"varint,6,opt,name=finished,proto3" json:"finished,omitempty" yaml:"finished,omitempty"`
}

func (m *ProposalHistoryRecord) Reset()         { *m = ProposalHistoryRecord{} }
func (m *ProposalHistoryRecord) String() string { return proto.CompactTextString(m) }
func (*ProposalHistoryRecord) ProtoMessage()    {}
func (*ProposalHistoryRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{1}
}
func (m *ProposalHistoryRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProposalHistoryRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProposalHistoryRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProposalHistoryRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalHistoryRecord.Merge(m, src)
}
func (m *ProposalHistoryRecord) XXX_Size() int {
	return m.Size()
}
func (m *ProposalHistoryRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalHistoryRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalHistoryRecord proto.InternalMessageInfo

// Government is a list of accounts.
//
// For the optimization sake, it's better not to use it as a part of a more complex data struct, using simple
// `repeated string` instead.
type Government struct {
	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members" yaml:"members"`
}

func (m *Government) Reset()      { *m = Government{} }
func (*Government) ProtoMessage() {}
func (*Government) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{2}
}
func (m *Government) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Government) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Government.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Government) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Government.Merge(m, src)
}
func (m *Government) XXX_Size() int {
	return m.Size()
}
func (m *Government) XXX_DiscardUnknown() {
	xxx_messageInfo_Government.DiscardUnknown(m)
}

var xxx_messageInfo_Government proto.InternalMessageInfo

// Poll is like Proposal, but it's specified by plain text and has no automatic decision execution engine encoded in the
// blockchain. Also, a wider range of people can vote for/against it.
type Poll struct {
	// Name is a title of the poll. Optional.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name,omitempty"`
	// Author is the poll creator's SDK address.
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author" yaml:"author"`
	// Question is the poll formulation.
	Question string `protobuf:"bytes,3,opt,name=question,proto3" json:"question" yaml:"question"`
	// StartTime denotes when the poll was created.
	// Set by the keeper itself, MUST be omitted in messages.
	StartTime *time.Time `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time,omitempty" yaml:"start_time,omitempty"`
	// EndTime is time when the poll is finished and votes are counted.
	// Set by the kepper itself, MUST be omitted in messages.
	EndTime *time.Time `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time,omitempty" yaml:"end_time,omitempty"`
	// Quorum is the share of 'yes' from the total number of votes required for positive decision. Quorum 0 means that
	// only 1 'yes' is sufficient. Optional. Should be omitted if the poll is totally informational and not intended for
	// any decision making.
	Quorum *github_com_arterynetwork_artr_util.Fraction `protobuf:"bytes,6,opt,name=quorum,proto3,customtype=github.com/arterynetwork/artr/util.Fraction" json:"quorum,omitempty" yaml:"quorum,omitempty"`
	// Types that are valid to be assigned to Requirements:
	//	*Poll_CanValidate
	//	*Poll_MinStatus
	Requirements isPoll_Requirements `protobuf_oneof:"requirements"`
}

func (m *Poll) Reset()      { *m = Poll{} }
func (*Poll) ProtoMessage() {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{3}
}
func (m *Poll) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return m.Size()
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

type isPoll_Requirements interface {
	isPoll_Requirements()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type Poll_CanValidate struct {
	CanValidate *Poll_Unit `protobuf:"bytes,7,opt,name=can_validate,json=canValidate,proto3,oneof" json:"can_validate" yaml:"can_validate"`
}
type Poll_MinStatus struct {
	MinStatus types1.Status `protobuf:"varint,8,opt,name=min_status,json=minStatus,proto3,enum=artery.referral.v1beta1.Status,oneof" json:"min_status" yaml:"min_status"`
}

func (*Poll_CanValidate) isPoll_Requirements() {}
func (*Poll_MinStatus) isPoll_Requirements()   {}

func (m *Poll) GetRequirements() isPoll_Requirements {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *Poll) GetCanValidate() *Poll_Unit {
	if x, ok := m.GetRequirements().(*Poll_CanValidate); ok {
		return x.CanValidate
	}
	return nil
}

func (m *Poll) GetMinStatus() types1.Status {
	if x, ok := m.GetRequirements().(*Poll_MinStatus); ok {
		return x.MinStatus
	}
	return types1.STATUS_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Poll) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Poll_CanValidate)(nil),
		(*Poll_MinStatus)(nil),
	}
}

type Poll_Unit struct {
}

func (m *Poll_Unit) Reset()         { *m = Poll_Unit{} }
func (m *Poll_Unit) String() string { return proto.CompactTextString(m) }
func (*Poll_Unit) ProtoMessage()    {}
func (*Poll_Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{3, 0}
}
func (m *Poll_Unit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Poll_Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Poll_Unit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Poll_Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll_Unit.Merge(m, src)
}
func (m *Poll_Unit) XXX_Size() int {
	return m.Size()
}
func (m *Poll_Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Poll_Unit proto.InternalMessageInfo

type PollHistoryItem struct {
	Poll     Poll     `protobuf:"bytes,1,opt,name=poll,proto3" json:"poll,inline" yaml:"poll,inline"`
	Yes      uint64   `protobuf:"varint,2,opt,name=yes,proto3" json:"yes" yaml:"yes"`
	No       uint64   `protobuf:"varint,3,opt,name=no,proto3" json:"no" yaml:"no"`
	Decision Decision `protobuf:"varint,4,opt,name=decision,proto3,enum=artery.voting.v1beta1.Decision" json:"decision,omitempty" yaml:"decision,omitempty"`
}

func (m *PollHistoryItem) Reset()         { *m = PollHistoryItem{} }
func (m *PollHistoryItem) String() string { return proto.CompactTextString(m) }
func (*PollHistoryItem) ProtoMessage()    {}
func (*PollHistoryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5505ea3c7b17e6f, []int{4}
}
func (m *PollHistoryItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PollHistoryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PollHistoryItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PollHistoryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollHistoryItem.Merge(m, src)
}
func (m *PollHistoryItem) XXX_Size() int {
	return m.Size()
}
func (m *PollHistoryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PollHistoryItem.DiscardUnknown(m)
}

var xxx_messageInfo_PollHistoryItem proto.InternalMessageInfo

func (m *PollHistoryItem) GetPoll() Poll {
	if m != nil {
		return m.Poll
	}
	return Poll{}
}

func (m *PollHistoryItem) GetYes() uint64 {
	if m != nil {
		return m.Yes
	}
	return 0
}

func (m *PollHistoryItem) GetNo() uint64 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *PollHistoryItem) GetDecision() Decision {
	if m != nil {
		return m.Decision
	}
	return DECISION_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("artery.voting.v1beta1.Decision", Decision_name, Decision_value)
	proto.RegisterType((*Proposal)(nil), "artery.voting.v1beta1.Proposal")
	proto.RegisterType((*ProposalHistoryRecord)(nil), "artery.voting.v1beta1.ProposalHistoryRecord")
	proto.RegisterType((*Government)(nil), "artery.voting.v1beta1.Government")
	proto.RegisterType((*Poll)(nil), "artery.voting.v1beta1.Poll")
	proto.RegisterType((*Poll_Unit)(nil), "artery.voting.v1beta1.Poll.Unit")
	proto.RegisterType((*PollHistoryItem)(nil), "artery.voting.v1beta1.PollHistoryItem")
}

func init() { proto.RegisterFile("artery/voting/v1beta1/types.proto", fileDescriptor_c5505ea3c7b17e6f) }

var fileDescriptor_c5505ea3c7b17e6f = []byte{
	// 1678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x6f, 0xdb, 0xc8,
	0x15, 0x17, 0x65, 0x45, 0x96, 0xc6, 0x8e, 0x3f, 0xc6, 0x76, 0xcc, 0x95, 0xbb, 0x1e, 0x2d, 0xdd,
	0x36, 0x6e, 0xd6, 0x95, 0xd6, 0x0e, 0xda, 0x05, 0x1c, 0xa0, 0x81, 0x69, 0x3b, 0xb1, 0xb1, 0xa8,
	0x2d, 0xd0, 0xce, 0xb6, 0xd8, 0x8b, 0x4a, 0x91, 0x63, 0x85, 0x8d, 0xc8, 0xa1, 0x87, 0x94, 0x5d,
	0x2d, 0xd0, 0x4b, 0x8b, 0x02, 0x7b, 0x2a, 0x72, 0xe8, 0xa1, 0x40, 0x51, 0x20, 0x40, 0xcf, 0x01,
	0xfa, 0x67, 0xe4, 0x98, 0x63, 0xd1, 0x03, 0x5b, 0x24, 0x87, 0x16, 0x3c, 0xea, 0x2f, 0x28, 0xe6,
	0x83, 0x92, 0x29, 0x51, 0x4e, 0x2e, 0x3d, 0x59, 0x7c, 0x1f, 0xbf, 0xdf, 0x4f, 0x33, 0xef, 0x3d,
	0x3e, 0x19, 0x7c, 0x66, 0xd2, 0x10, 0xd3, 0x5e, 0xfd, 0x8a, 0x84, 0x8e, 0xd7, 0xae, 0x5f, 0x6d,
	0xb7, 0x70, 0x68, 0x6e, 0xd7, 0xc3, 0x9e, 0x8f, 0x83, 0x9a, 0x4f, 0x49, 0x48, 0xe0, 0x8a, 0x08,
	0xa9, 0x89, 0x90, 0x9a, 0x0c, 0xa9, 0x2c, 0xb7, 0x49, 0x9b, 0xf0, 0x88, 0x3a, 0xfb, 0x24, 0x82,
	0x2b, 0xa8, 0x4d, 0x48, 0xbb, 0x83, 0xeb, 0xfc, 0xa9, 0xd5, 0xbd, 0xa8, 0x87, 0x8e, 0x8b, 0x83,
	0xd0, 0x74, 0x7d, 0x19, 0xf0, 0x83, 0x6c, 0x42, 0x9f, 0x12, 0x9f, 0x04, 0x66, 0x47, 0x92, 0x56,
	0xaa, 0xd9, 0x61, 0x26, 0x6d, 0x27, 0x11, 0x89, 0x72, 0x8f, 0xd8, 0x13, 0x94, 0x57, 0x36, 0x64,
	0x08, 0xc5, 0x17, 0x98, 0x52, 0xb3, 0x93, 0x19, 0xb4, 0x6a, 0x91, 0xc0, 0x25, 0x41, 0xdd, 0x0d,
	0x18, 0x08, 0xfb, 0x23, 0x1c, 0xda, 0x1f, 0x16, 0x41, 0xa9, 0x21, 0x65, 0xc1, 0x1f, 0x83, 0x82,
	0x67, 0xba, 0x58, 0x55, 0xaa, 0xca, 0x66, 0x59, 0xff, 0xa4, 0x1f, 0xa1, 0x95, 0x9e, 0xe9, 0x76,
	0x76, 0x35, 0x66, 0xdd, 0x22, 0xae, 0x13, 0x62, 0xd7, 0x0f, 0x7b, 0x9a, 0xc1, 0xc3, 0xe0, 0x43,
	0x50, 0x34, 0xbb, 0xe1, 0x73, 0x42, 0xd5, 0x3c, 0x4f, 0x58, 0x8b, 0x23, 0x24, 0x2d, 0xfd, 0x08,
	0xdd, 0x15, 0xa9, 0xe2, 0x59, 0x33, 0xa4, 0x03, 0x36, 0x40, 0x81, 0x09, 0x53, 0xa7, 0xaa, 0xca,
	0xe6, 0xdc, 0xce, 0x46, 0x2d, 0xf3, 0xdc, 0x6b, 0x89, 0xa4, 0xf3, 0x9e, 0x8f, 0xf5, 0xd5, 0x38,
	0x42, 0x3c, 0xa9, 0x1f, 0xa1, 0x19, 0x81, 0xca, 0x9e, 0x34, 0x83, 0x1b, 0xe1, 0x1a, 0x28, 0x63,
	0xcf, 0x6e, 0xb6, 0x3a, 0xc4, 0x7a, 0xa1, 0x2e, 0x54, 0x95, 0xcd, 0x82, 0x51, 0xc2, 0x9e, 0xad,
	0xb3, 0x67, 0xf8, 0x18, 0xb0, 0xcf, 0x4d, 0x76, 0x41, 0x6a, 0xa1, 0xaa, 0x6c, 0xce, 0xec, 0x54,
	0x6a, 0xe2, 0xf6, 0x6a, 0xc9, 0xed, 0xd5, 0xce, 0x93, 0xdb, 0xd3, 0x4b, 0x6f, 0x22, 0xa4, 0xbc,
	0xfc, 0x17, 0x52, 0x8c, 0x69, 0xec, 0xd9, 0xcc, 0x0e, 0x2f, 0xc0, 0x1d, 0x9f, 0x3a, 0x16, 0x56,
	0xef, 0xf0, 0xec, 0xea, 0x44, 0xc1, 0x8e, 0x85, 0xf7, 0x68, 0x3b, 0xd0, 0xb7, 0xe2, 0x08, 0xcd,
	0xf3, 0x94, 0xe1, 0x89, 0x0d, 0x4f, 0x72, 0xc4, 0x71, 0x94, 0x33, 0x04, 0x3c, 0xfc, 0xab, 0x02,
	0x16, 0x6c, 0xdc, 0xc1, 0x6d, 0x33, 0x74, 0x88, 0xd7, 0x34, 0xaf, 0x4d, 0x6a, 0xab, 0x45, 0xce,
	0xf9, 0x60, 0x02, 0xe7, 0xc1, 0x20, 0x7c, 0x8f, 0x45, 0x73, 0xf6, 0x83, 0x38, 0x42, 0x95, 0x51,
	0x9c, 0x94, 0x90, 0xaa, 0x10, 0x32, 0x39, 0x46, 0x55, 0x8e, 0x72, 0xc6, 0xbc, 0x9d, 0x06, 0x87,
	0x7f, 0x54, 0xc0, 0x5d, 0x0f, 0x87, 0xd7, 0x84, 0xbe, 0x90, 0xe2, 0xa6, 0xb9, 0xb8, 0xfb, 0x13,
	0xc4, 0x9d, 0x88, 0xd8, 0xa1, 0xb2, 0x9f, 0xc5, 0x11, 0x5a, 0x4d, 0x21, 0xa4, 0x64, 0x7d, 0x2a,
	0x2b, 0x2d, 0x3b, 0x80, 0x6b, 0x9a, 0xf5, 0x6e, 0x60, 0x42, 0x1f, 0x4c, 0x9b, 0xb6, 0x4d, 0x71,
	0x10, 0xa8, 0x25, 0xae, 0x44, 0x9b, 0xa0, 0x64, 0x4f, 0x44, 0x71, 0x11, 0x5f, 0xc4, 0x11, 0x5a,
	0x94, 0x69, 0x29, 0xfa, 0x55, 0x59, 0xad, 0xa3, 0xae, 0xa3, 0x9c, 0x91, 0xd0, 0xc0, 0xbf, 0x28,
	0x60, 0x21, 0x20, 0x17, 0xe1, 0xb5, 0x49, 0x71, 0xb3, 0xeb, 0xb7, 0xa9, 0x69, 0x63, 0xb5, 0x7c,
	0xeb, 0x15, 0x9d, 0xc9, 0xf0, 0x67, 0x22, 0x9a, 0x6b, 0xd0, 0xd9, 0x15, 0x8d, 0xe2, 0x64, 0x5d,
	0xd1, 0xe4, 0x18, 0x76, 0x41, 0x41, 0x1a, 0x1a, 0xfe, 0x16, 0x00, 0xd7, 0xf1, 0x9a, 0xa6, 0x4b,
	0xba, 0x5e, 0xa8, 0x02, 0x2e, 0xeb, 0xfb, 0x13, 0x64, 0xfd, 0xdc, 0xf1, 0xf6, 0x78, 0x1c, 0x17,
	0xf4, 0xd3, 0x38, 0x42, 0xcb, 0xc3, 0xdc, 0x94, 0x94, 0x8a, 0x90, 0x92, 0xe5, 0x3d, 0xca, 0x19,
	0x65, 0x37, 0x01, 0x62, 0x7d, 0x62, 0x71, 0xe6, 0x99, 0x5b, 0xfb, 0x64, 0x7f, 0xc0, 0xca, 0xfb,
	0xc4, 0x1a, 0x23, 0x94, 0x7d, 0x62, 0x8d, 0x71, 0x09, 0x78, 0xe8, 0x82, 0x62, 0x10, 0x9a, 0x61,
	0x37, 0x50, 0x67, 0x39, 0xd1, 0x67, 0x93, 0x4e, 0x9e, 0x07, 0x0d, 0x2e, 0x7d, 0x41, 0x24, 0xa5,
	0xa8, 0xee, 0xc9, 0x63, 0x1e, 0xf1, 0xf0, 0x5a, 0x93, 0x24, 0xf0, 0x2b, 0x30, 0xcb, 0xbe, 0xbb,
	0x45, 0x9d, 0x10, 0x53, 0xc7, 0x54, 0x97, 0x39, 0xe9, 0x0f, 0x27, 0x9f, 0xeb, 0xbe, 0x8c, 0x64,
	0xcc, 0x47, 0x39, 0x63, 0xc6, 0x1d, 0x9a, 0x98, 0x76, 0x1f, 0x53, 0x87, 0xd8, 0xea, 0xdd, 0x5b,
	0xb5, 0x37, 0x78, 0xd0, 0x50, 0xbb, 0x48, 0xca, 0xd2, 0x3e, 0xea, 0x11, 0xda, 0x85, 0x15, 0xfe,
	0x5e, 0x01, 0x33, 0x02, 0xb9, 0x41, 0xae, 0x31, 0x55, 0xe7, 0x38, 0xe9, 0x60, 0xe4, 0x8a, 0x77,
	0xca, 0x70, 0x9a, 0x38, 0x41, 0x48, 0x9d, 0x56, 0x97, 0xb5, 0xbc, 0xbe, 0x1b, 0x47, 0xe8, 0x9e,
	0xc8, 0x6d, 0xfa, 0x2c, 0x39, 0x45, 0xfe, 0x3d, 0x41, 0x9e, 0xed, 0x67, 0x5f, 0xfa, 0x06, 0x2b,
	0xeb, 0x53, 0x9f, 0x50, 0x86, 0xaa, 0xce, 0xdf, 0xda, 0xa7, 0x0d, 0x11, 0x35, 0xec, 0x53, 0x99,
	0x96, 0xd5, 0xa7, 0x63, 0x2e, 0xd6, 0xa7, 0xd2, 0x08, 0xbb, 0xa0, 0x24, 0x3f, 0x06, 0xea, 0x62,
	0xfa, 0x3b, 0x67, 0x53, 0x8a, 0x32, 0xd9, 0x89, 0x23, 0x04, 0x93, 0xc4, 0x14, 0xa9, 0x9a, 0x22,
	0x4d, 0x4f, 0x87, 0x01, 0x15, 0xbc, 0x04, 0xaa, 0x69, 0x59, 0xb4, 0x8b, 0x9b, 0x3e, 0xa6, 0x16,
	0xf6, 0x42, 0xb3, 0x8d, 0x9b, 0xd4, 0xf4, 0xda, 0x38, 0x50, 0x21, 0x97, 0xb1, 0x3d, 0x69, 0x42,
	0xf1, 0xb4, 0xc6, 0x20, 0xcb, 0xe0, 0x49, 0x5c, 0x54, 0x9e, 0xdf, 0xe8, 0x3d, 0x33, 0x33, 0x02,
	0xfe, 0x1a, 0xac, 0x8e, 0x53, 0x86, 0x66, 0xab, 0x83, 0xd5, 0x25, 0xce, 0xf8, 0xc5, 0x47, 0x32,
	0x9e, 0xb3, 0x1c, 0x59, 0xb2, 0x2b, 0x66, 0x96, 0x13, 0x3e, 0x02, 0x45, 0x8a, 0xaf, 0xc8, 0x0b,
	0xac, 0xae, 0xdc, 0x5a, 0xbc, 0x06, 0x0f, 0x92, 0x58, 0x32, 0x65, 0x77, 0xf5, 0xbb, 0x57, 0x28,
	0xf7, 0xe7, 0x57, 0x28, 0xf7, 0xdf, 0x57, 0x48, 0xf9, 0xdd, 0x7f, 0xfe, 0xfe, 0x40, 0xae, 0x03,
	0x7a, 0x11, 0x14, 0xd8, 0xba, 0xa3, 0xfd, 0xa9, 0x00, 0x56, 0x92, 0x97, 0xfe, 0x91, 0x13, 0x84,
	0x84, 0xf6, 0x0c, 0x6c, 0x11, 0x6a, 0xc3, 0x5f, 0x81, 0x52, 0xb2, 0x37, 0xf1, 0xc5, 0x64, 0x66,
	0x07, 0x7d, 0x60, 0x69, 0xd0, 0x37, 0xde, 0x44, 0x28, 0x17, 0x47, 0x68, 0x90, 0xd8, 0x8f, 0xd0,
	0x7c, 0xf2, 0xfe, 0x15, 0x16, 0xcd, 0x18, 0x38, 0xe1, 0x2f, 0x00, 0x68, 0x93, 0x2b, 0x4c, 0x3d,
	0x17, 0x7b, 0xa1, 0x9a, 0xaf, 0x4e, 0x6d, 0x96, 0xf5, 0x2f, 0xd9, 0x4c, 0x1c, 0x5a, 0x53, 0xe5,
	0xb0, 0x26, 0xa0, 0xb2, 0xbc, 0x9a, 0x71, 0x03, 0x0a, 0x3e, 0x05, 0x45, 0xb3, 0x4d, 0x31, 0xb6,
	0xd5, 0x29, 0x0e, 0x5a, 0x67, 0xcd, 0x2c, 0x2c, 0x99, 0x2f, 0x9f, 0x11, 0x0f, 0x5b, 0x9a, 0xb8,
	0x09, 0x9e, 0x81, 0xb2, 0xed, 0x04, 0x12, 0xab, 0xc0, 0xb1, 0x7e, 0x12, 0x47, 0x68, 0x69, 0x60,
	0xcc, 0x9a, 0xd9, 0x19, 0x4e, 0xcd, 0x18, 0xe2, 0xc0, 0xaf, 0xc0, 0x74, 0x10, 0xb2, 0x93, 0xb4,
	0xf9, 0x6e, 0x33, 0xa5, 0x6f, 0xb3, 0xa6, 0x93, 0xa6, 0xac, 0xfa, 0x1f, 0x73, 0x69, 0x46, 0x82,
	0x00, 0x4f, 0x41, 0xe9, 0xc2, 0xf1, 0x9c, 0xe0, 0x39, 0x16, 0x5b, 0xcb, 0x94, 0xfe, 0x90, 0xb5,
	0x53, 0x62, 0x4b, 0xc1, 0x7d, 0x22, 0xe0, 0xc6, 0x7d, 0x9a, 0x31, 0x00, 0xd9, 0x2d, 0xb0, 0x8a,
	0xd1, 0x4e, 0x01, 0x78, 0x3a, 0x3c, 0xcf, 0x2f, 0xc1, 0xb4, 0x8b, 0xdd, 0x16, 0xa6, 0x81, 0xaa,
	0xf0, 0x43, 0xf8, 0x34, 0x8e, 0x50, 0x62, 0xea, 0x47, 0x68, 0x4e, 0xbe, 0xac, 0x84, 0x41, 0x33,
	0x12, 0xd7, 0x6e, 0x29, 0x29, 0x3f, 0xed, 0x75, 0x11, 0x14, 0x1a, 0xa4, 0xd3, 0x81, 0x8f, 0x53,
	0xbb, 0xee, 0xe7, 0x71, 0x84, 0xe6, 0xd2, 0x5b, 0xee, 0xff, 0x65, 0xfb, 0x7d, 0x04, 0x4a, 0x97,
	0x5d, 0x1c, 0xf0, 0x69, 0x38, 0xc5, 0xd3, 0x10, 0xab, 0xd3, 0xc4, 0x36, 0xac, 0xd3, 0xc4, 0xa2,
	0x19, 0x03, 0x27, 0xfc, 0x16, 0x00, 0x7e, 0xdc, 0x1f, 0xbb, 0xcd, 0x3e, 0x66, 0xdb, 0x2c, 0xab,
	0xe3, 0x61, 0x56, 0x56, 0x1d, 0x67, 0x79, 0x35, 0xbe, 0x04, 0x97, 0xb9, 0x8b, 0xaf, 0xc1, 0xf4,
	0xc6, 0x1e, 0x7d, 0xe7, 0x83, 0xcc, 0x8f, 0x24, 0x33, 0x4c, 0x72, 0xb2, 0xee, 0x7f, 0xdc, 0xa7,
	0xa5, 0x57, 0xef, 0x6f, 0x41, 0xf1, 0xb2, 0x4b, 0x68, 0xd7, 0xe5, 0x15, 0x55, 0xd6, 0x5b, 0x0c,
	0xf5, 0x9f, 0x11, 0xfa, 0xbc, 0xed, 0x84, 0xcf, 0xbb, 0xad, 0x9a, 0x45, 0xdc, 0xba, 0x98, 0x04,
	0x72, 0x31, 0x64, 0x4f, 0xb4, 0xde, 0x0d, 0x9d, 0x4e, 0xed, 0x09, 0x35, 0x2d, 0x76, 0x68, 0xac,
	0xe3, 0x04, 0x48, 0x56, 0xc7, 0x8d, 0x7a, 0x34, 0x43, 0x32, 0x42, 0x0f, 0xcc, 0x5a, 0xa6, 0xd7,
	0xbc, 0x32, 0x3b, 0x8e, 0x6d, 0x86, 0x58, 0x2e, 0xbb, 0x13, 0xb7, 0x7f, 0xd2, 0xe9, 0xd4, 0x9e,
	0x79, 0x4e, 0xa8, 0xdf, 0x8f, 0x23, 0x94, 0xca, 0xec, 0x47, 0x68, 0x49, 0xae, 0x34, 0x37, 0xac,
	0x1a, 0x7b, 0x4b, 0x5a, 0xa6, 0xf7, 0xb5, 0x7c, 0x86, 0x58, 0x6c, 0x6f, 0x72, 0xb5, 0x29, 0xf1,
	0x1f, 0x47, 0x83, 0x39, 0x97, 0xfc, 0xb4, 0x1b, 0x59, 0x6e, 0xf4, 0x8d, 0x38, 0x42, 0x37, 0xd2,
	0xfa, 0x11, 0x5a, 0x1c, 0xae, 0x6b, 0xc2, 0xa6, 0xc9, 0x2d, 0x4d, 0x64, 0x54, 0x8a, 0xa0, 0xc0,
	0x64, 0x4e, 0x9e, 0xc7, 0x73, 0x60, 0x96, 0xe2, 0xcb, 0xae, 0x43, 0x31, 0xeb, 0xb8, 0x40, 0x7b,
	0x9d, 0x07, 0xf3, 0xec, 0xdb, 0xc9, 0x99, 0x7c, 0x1c, 0x62, 0x17, 0x7e, 0x03, 0x0a, 0x3e, 0xe9,
	0x24, 0xd3, 0x78, 0xed, 0x96, 0x33, 0xd1, 0x7f, 0x24, 0x27, 0xf1, 0x0c, 0x4b, 0xd8, 0x72, 0xbc,
	0x8e, 0xe3, 0xb1, 0x13, 0x81, 0xc9, 0x0b, 0x75, 0x60, 0xd4, 0x0c, 0x8e, 0x09, 0xef, 0x83, 0xa9,
	0x1e, 0x0e, 0x78, 0x4b, 0x15, 0xf4, 0x95, 0x38, 0x42, 0xec, 0xb1, 0x1f, 0x21, 0x20, 0x32, 0x7a,
	0x38, 0xd0, 0x0c, 0x66, 0x82, 0x1b, 0x20, 0xef, 0x11, 0xde, 0x43, 0x05, 0x7d, 0x29, 0x8e, 0x50,
	0xde, 0x23, 0xfd, 0x08, 0x95, 0x65, 0xc7, 0x12, 0xcd, 0xc8, 0x7b, 0x04, 0xfa, 0xa0, 0x64, 0x63,
	0xcb, 0x09, 0x58, 0xbb, 0x15, 0xd2, 0x67, 0x3a, 0xf6, 0x5b, 0x4a, 0x84, 0x89, 0xb1, 0x95, 0x24,
	0x65, 0x95, 0xed, 0xb8, 0x4f, 0x33, 0x06, 0x2c, 0x0f, 0x7e, 0x09, 0x4a, 0x09, 0x14, 0x54, 0xc1,
	0xf2, 0xc1, 0xe1, 0xfe, 0xf1, 0xd9, 0xf1, 0xe9, 0x49, 0xf3, 0xd9, 0xc9, 0x59, 0xe3, 0x70, 0xff,
	0xf8, 0xc9, 0xf1, 0xe1, 0xc1, 0x42, 0x0e, 0xae, 0x80, 0xc5, 0x81, 0xa7, 0x71, 0x7a, 0x76, 0x7c,
	0x7e, 0xfc, 0xf5, 0xe1, 0x82, 0x92, 0x32, 0x9f, 0x1c, 0x3e, 0xdd, 0xe3, 0xe6, 0x7c, 0xa5, 0xf0,
	0xdd, 0xdf, 0xd6, 0x73, 0xfa, 0x93, 0x37, 0xef, 0xd6, 0x95, 0xb7, 0xef, 0xd6, 0x95, 0x7f, 0xbf,
	0x5b, 0x57, 0x5e, 0xbe, 0x5f, 0xcf, 0xbd, 0x7d, 0xbf, 0x9e, 0xfb, 0xc7, 0xfb, 0xf5, 0xdc, 0x37,
	0x5b, 0xb7, 0xf7, 0xc3, 0x6f, 0x92, 0xff, 0x2f, 0xf0, 0x7f, 0x08, 0xb4, 0x8a, 0xbc, 0x5f, 0x1f,
	0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x06, 0xe1, 0x67, 0x15, 0x11, 0x00, 0x00,
}

func (this *Proposal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal)
	if !ok {
		that2, ok := that.(Proposal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Author != that1.Author {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.EndBlock != that1.EndBlock {
		return false
	}
	if that1.EndTime == nil {
		if this.EndTime != nil {
			return false
		}
	} else if !this.EndTime.Equal(*that1.EndTime) {
		return false
	}
	if that1.Args == nil {
		if this.Args != nil {
			return false
		}
	} else if this.Args == nil {
		return false
	} else if !this.Args.Equal(that1.Args) {
		return false
	}
	return true
}
func (this *Proposal_Price) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Price)
	if !ok {
		that2, ok := that.(Proposal_Price)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Price.Equal(that1.Price) {
		return false
	}
	return true
}
func (this *Proposal_DelegationAward) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_DelegationAward)
	if !ok {
		that2, ok := that.(Proposal_DelegationAward)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DelegationAward.Equal(that1.DelegationAward) {
		return false
	}
	return true
}
func (this *Proposal_NetworkAward) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_NetworkAward)
	if !ok {
		that2, ok := that.(Proposal_NetworkAward)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.NetworkAward.Equal(that1.NetworkAward) {
		return false
	}
	return true
}
func (this *Proposal_Address) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Address)
	if !ok {
		that2, ok := that.(Proposal_Address)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Address.Equal(that1.Address) {
		return false
	}
	return true
}
func (this *Proposal_SoftwareUpgrade) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_SoftwareUpgrade)
	if !ok {
		that2, ok := that.(Proposal_SoftwareUpgrade)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SoftwareUpgrade.Equal(that1.SoftwareUpgrade) {
		return false
	}
	return true
}
func (this *Proposal_MinAmount) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_MinAmount)
	if !ok {
		that2, ok := that.(Proposal_MinAmount)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinAmount.Equal(that1.MinAmount) {
		return false
	}
	return true
}
func (this *Proposal_Count) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Count)
	if !ok {
		that2, ok := that.(Proposal_Count)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Count.Equal(that1.Count) {
		return false
	}
	return true
}
func (this *Proposal_Status) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Status)
	if !ok {
		that2, ok := that.(Proposal_Status)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(that1.Status) {
		return false
	}
	return true
}
func (this *Proposal_MinCriteria) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_MinCriteria)
	if !ok {
		that2, ok := that.(Proposal_MinCriteria)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.MinCriteria.Equal(that1.MinCriteria) {
		return false
	}
	return true
}
func (this *Proposal_Period) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Period)
	if !ok {
		that2, ok := that.(Proposal_Period)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Period.Equal(that1.Period) {
		return false
	}
	return true
}
func (this *Proposal_VotingPower) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_VotingPower)
	if !ok {
		that2, ok := that.(Proposal_VotingPower)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.VotingPower.Equal(that1.VotingPower) {
		return false
	}
	return true
}
func (this *Proposal_Portion) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Portion)
	if !ok {
		that2, ok := that.(Proposal_Portion)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Portion.Equal(that1.Portion) {
		return false
	}
	return true
}
func (this *Proposal_Portions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Portions)
	if !ok {
		that2, ok := that.(Proposal_Portions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Portions.Equal(that1.Portions) {
		return false
	}
	return true
}
func (this *Proposal_AccruePercentageRanges) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_AccruePercentageRanges)
	if !ok {
		that2, ok := that.(Proposal_AccruePercentageRanges)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AccruePercentageRanges.Equal(that1.AccruePercentageRanges) {
		return false
	}
	return true
}
func (this *Proposal_AccruePercentageTable) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_AccruePercentageTable)
	if !ok {
		that2, ok := that.(Proposal_AccruePercentageTable)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AccruePercentageTable.Equal(that1.AccruePercentageTable) {
		return false
	}
	return true
}
func (this *Proposal_Revoke) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Proposal_Revoke)
	if !ok {
		that2, ok := that.(Proposal_Revoke)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Revoke.Equal(that1.Revoke) {
		return false
	}
	return true
}
func (this *Poll) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Poll)
	if !ok {
		that2, ok := that.(Poll)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Author != that1.Author {
		return false
	}
	if this.Question != that1.Question {
		return false
	}
	if that1.StartTime == nil {
		if this.StartTime != nil {
			return false
		}
	} else if !this.StartTime.Equal(*that1.StartTime) {
		return false
	}
	if that1.EndTime == nil {
		if this.EndTime != nil {
			return false
		}
	} else if !this.EndTime.Equal(*that1.EndTime) {
		return false
	}
	if that1.Quorum == nil {
		if this.Quorum != nil {
			return false
		}
	} else if !this.Quorum.Equal(*that1.Quorum) {
		return false
	}
	if that1.Requirements == nil {
		if this.Requirements != nil {
			return false
		}
	} else if this.Requirements == nil {
		return false
	} else if !this.Requirements.Equal(that1.Requirements) {
		return false
	}
	return true
}
func (this *Poll_CanValidate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Poll_CanValidate)
	if !ok {
		that2, ok := that.(Poll_CanValidate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CanValidate.Equal(that1.CanValidate) {
		return false
	}
	return true
}
func (this *Poll_MinStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Poll_MinStatus)
	if !ok {
		that2, ok := that.(Poll_MinStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinStatus != that1.MinStatus {
		return false
	}
	return true
}
func (m *Proposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Args != nil {
		{
			size := m.Args.Size()
			i -= size
			if _, err := m.Args.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.EndBlock != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.EndTime != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintTypes(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Proposal_Price) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Price) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Price != nil {
		{
			size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_DelegationAward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_DelegationAward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DelegationAward != nil {
		{
			size, err := m.DelegationAward.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_NetworkAward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_NetworkAward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NetworkAward != nil {
		{
			size, err := m.NetworkAward.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Address) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Address) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Address != nil {
		{
			size, err := m.Address.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_SoftwareUpgrade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_SoftwareUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SoftwareUpgrade != nil {
		{
			size, err := m.SoftwareUpgrade.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_MinAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_MinAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MinAmount != nil {
		{
			size, err := m.MinAmount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Count) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Count) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Count != nil {
		{
			size, err := m.Count.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Period) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Period) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Period != nil {
		{
			size, err := m.Period.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_VotingPower) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_VotingPower) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.VotingPower != nil {
		{
			size, err := m.VotingPower.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Portion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Portion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Portion != nil {
		{
			size, err := m.Portion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Portions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Portions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Portions != nil {
		{
			size, err := m.Portions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_AccruePercentageRanges) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_AccruePercentageRanges) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AccruePercentageRanges != nil {
		{
			size, err := m.AccruePercentageRanges.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_AccruePercentageTable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_AccruePercentageTable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AccruePercentageTable != nil {
		{
			size, err := m.AccruePercentageTable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_MinCriteria) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_MinCriteria) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MinCriteria != nil {
		{
			size, err := m.MinCriteria.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	return len(dAtA) - i, nil
}
func (m *Proposal_Revoke) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal_Revoke) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Revoke != nil {
		{
			size, err := m.Revoke.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	return len(dAtA) - i, nil
}
func (m *ProposalHistoryRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProposalHistoryRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProposalHistoryRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Finished != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Finished))
		i--
		dAtA[i] = 0x30
	}
	if m.Started != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Started))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Disagreed) > 0 {
		for iNdEx := len(m.Disagreed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Disagreed[iNdEx])
			copy(dAtA[i:], m.Disagreed[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Disagreed[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Agreed) > 0 {
		for iNdEx := len(m.Agreed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Agreed[iNdEx])
			copy(dAtA[i:], m.Agreed[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Agreed[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Government) > 0 {
		for iNdEx := len(m.Government) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Government[iNdEx])
			copy(dAtA[i:], m.Government[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Government[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Proposal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Government) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Government) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Government) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Members) > 0 {
		for iNdEx := len(m.Members) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Members[iNdEx])
			copy(dAtA[i:], m.Members[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Members[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Poll) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Poll) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Poll) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Requirements != nil {
		{
			size := m.Requirements.Size()
			i -= size
			if _, err := m.Requirements.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Quorum != nil {
		{
			size := m.Quorum.Size()
			i -= size
			if _, err := m.Quorum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.EndTime != nil {
		n19, err19 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime):])
		if err19 != nil {
			return 0, err19
		}
		i -= n19
		i = encodeVarintTypes(dAtA, i, uint64(n19))
		i--
		dAtA[i] = 0x2a
	}
	if m.StartTime != nil {
		n20, err20 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StartTime):])
		if err20 != nil {
			return 0, err20
		}
		i -= n20
		i = encodeVarintTypes(dAtA, i, uint64(n20))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Question) > 0 {
		i -= len(m.Question)
		copy(dAtA[i:], m.Question)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Question)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Author) > 0 {
		i -= len(m.Author)
		copy(dAtA[i:], m.Author)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Author)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Poll_CanValidate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Poll_CanValidate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CanValidate != nil {
		{
			size, err := m.CanValidate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *Poll_MinStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Poll_MinStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintTypes(dAtA, i, uint64(m.MinStatus))
	i--
	dAtA[i] = 0x40
	return len(dAtA) - i, nil
}
func (m *Poll_Unit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Poll_Unit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Poll_Unit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PollHistoryItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PollHistoryItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PollHistoryItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decision != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Decision))
		i--
		dAtA[i] = 0x20
	}
	if m.No != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.No))
		i--
		dAtA[i] = 0x18
	}
	if m.Yes != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Yes))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Poll.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Proposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovTypes(uint64(m.Type))
	}
	if m.EndTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Args != nil {
		n += m.Args.Size()
	}
	if m.EndBlock != 0 {
		n += 2 + sovTypes(uint64(m.EndBlock))
	}
	return n
}

func (m *Proposal_Price) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Price != nil {
		l = m.Price.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_DelegationAward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DelegationAward != nil {
		l = m.DelegationAward.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_NetworkAward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NetworkAward != nil {
		l = m.NetworkAward.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Address) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Address != nil {
		l = m.Address.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_SoftwareUpgrade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SoftwareUpgrade != nil {
		l = m.SoftwareUpgrade.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_MinAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinAmount != nil {
		l = m.MinAmount.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Count) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != nil {
		l = m.Count.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Period) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Period != nil {
		l = m.Period.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_VotingPower) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VotingPower != nil {
		l = m.VotingPower.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Portion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Portion != nil {
		l = m.Portion.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Portions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Portions != nil {
		l = m.Portions.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_AccruePercentageRanges) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccruePercentageRanges != nil {
		l = m.AccruePercentageRanges.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_AccruePercentageTable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccruePercentageTable != nil {
		l = m.AccruePercentageTable.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_MinCriteria) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinCriteria != nil {
		l = m.MinCriteria.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Proposal_Revoke) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revoke != nil {
		l = m.Revoke.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *ProposalHistoryRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Proposal.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Government) > 0 {
		for _, s := range m.Government {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.Agreed) > 0 {
		for _, s := range m.Agreed {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.Disagreed) > 0 {
		for _, s := range m.Disagreed {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Started != 0 {
		n += 1 + sovTypes(uint64(m.Started))
	}
	if m.Finished != 0 {
		n += 1 + sovTypes(uint64(m.Finished))
	}
	return n
}

func (m *Government) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Members) > 0 {
		for _, s := range m.Members {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Poll) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Author)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Question)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.StartTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StartTime)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.EndTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Quorum != nil {
		l = m.Quorum.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Requirements != nil {
		n += m.Requirements.Size()
	}
	return n
}

func (m *Poll_CanValidate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CanValidate != nil {
		l = m.CanValidate.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *Poll_MinStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovTypes(uint64(m.MinStatus))
	return n
}
func (m *Poll_Unit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PollHistoryItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Poll.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.Yes != 0 {
		n += 1 + sovTypes(uint64(m.Yes))
	}
	if m.No != 0 {
		n += 1 + sovTypes(uint64(m.No))
	}
	if m.Decision != 0 {
		n += 1 + sovTypes(uint64(m.Decision))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Proposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Proposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Proposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ProposalType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PriceArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Price{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationAward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DelegationAwardArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_DelegationAward{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkAward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NetworkAwardArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_NetworkAward{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AddressArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Address{v}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftwareUpgrade", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &SoftwareUpgradeArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_SoftwareUpgrade{v}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MinAmountArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_MinAmount{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CountArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Count{v}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &StatusArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Status{v}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PeriodArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Period{v}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.Distribution{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_VotingPower{v}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Portion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PortionArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Portion{v}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Portions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PortionsArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Portions{v}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruePercentageRanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AccruePercentageRangesArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_AccruePercentageRanges{v}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruePercentageTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AccruePercentageTableArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_AccruePercentageTable{v}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCriteria", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MinCriteriaArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_MinCriteria{v}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoke", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RevokeArgs{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Args = &Proposal_Revoke{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProposalHistoryRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProposalHistoryRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProposalHistoryRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Government", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Government = append(m.Government, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agreed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agreed = append(m.Agreed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disagreed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Disagreed = append(m.Disagreed, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Started", wireType)
			}
			m.Started = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Started |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finished", wireType)
			}
			m.Finished = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Finished |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Government) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Government: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Government: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Members", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Members = append(m.Members, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Poll) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Poll: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Poll: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Author", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Author = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Question", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Question = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_arterynetwork_artr_util.Fraction
			m.Quorum = &v
			if err := m.Quorum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanValidate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Poll_Unit{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Requirements = &Poll_CanValidate{v}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStatus", wireType)
			}
			var v types1.Status
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= types1.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Requirements = &Poll_MinStatus{v}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Poll_Unit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Unit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Unit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PollHistoryItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PollHistoryItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PollHistoryItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Poll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Poll.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yes", wireType)
			}
			m.Yes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			m.No = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.No |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			m.Decision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decision |= Decision(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
