syntax="proto3";
package artery.noding.v1beta1;

import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";
import "tendermint/abci/types.proto";
import "artery/noding/v1beta1/types.proto";

option go_package = "github.com/arterynetwork/artr/x/noding/types";

message EventValidatorBanished {
  string address = 1;
  Reason reason = 2;
}

message EventValidatorJailed {
  string address = 1;
}

message EventByzantine {
  string address = 1;
  bool banned = 2;
  repeated tendermint.abci.Misbehavior evidences = 3 [(gogoproto.nullable) = false];

  // Penalty - изъятая доля собственной делегации. Без неё снаружи не
  // видно, что нарушитель поплатился, а не просто был отмечен.
  repeated cosmos.base.v1beta1.Coin penalty = 4 [(gogoproto.nullable) = false];
}
