// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: artery/profile/v1beta1/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventPayTariff struct {
	Address          string    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ExpireAt         time.Time `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3,stdtime" json:"expire_at"`
	Total            uint64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	CommissionTo     []string  `protobuf:"bytes,4,rep,name=commission_to,json=commissionTo,proto3" json:"commission_to,omitempty"`
	CommissionAmount []uint64  `protobuf:"varint,5,rep,packed,name=commission_amount,json=commissionAmount,proto3" json:"commission_amount,omitempty"`
}

func (m *EventPayTariff) Reset()         { *m = EventPayTariff{} }
func (m *EventPayTariff) String() string { return proto.CompactTextString(m) }
func (*EventPayTariff) ProtoMessage()    {}
func (*EventPayTariff) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{0}
}
func (m *EventPayTariff) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventPayTariff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventPayTariff.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventPayTariff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPayTariff.Merge(m, src)
}
func (m *EventPayTariff) XXX_Size() int {
	return m.Size()
}
func (m *EventPayTariff) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPayTariff.DiscardUnknown(m)
}

var xxx_messageInfo_EventPayTariff proto.InternalMessageInfo

func (m *EventPayTariff) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventPayTariff) GetExpireAt() time.Time {
	if m != nil {
		return m.ExpireAt
	}
	return time.Time{}
}

func (m *EventPayTariff) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *EventPayTariff) GetCommissionTo() []string {
	if m != nil {
		return m.CommissionTo
	}
	return nil
}

func (m *EventPayTariff) GetCommissionAmount() []uint64 {
	if m != nil {
		return m.CommissionAmount
	}
	return nil
}

type EventActivityChanged struct {
	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ActiveNow bool   `protobuf:"varint,2,opt,name=active_now,json=activeNow,proto3" json:"active_now,omitempty"`
}

func (m *EventActivityChanged) Reset()         { *m = EventActivityChanged{} }
func (m *EventActivityChanged) String() string { return proto.CompactTextString(m) }
func (*EventActivityChanged) ProtoMessage()    {}
func (*EventActivityChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{1}
}
func (m *EventActivityChanged) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventActivityChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventActivityChanged.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventActivityChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventActivityChanged.Merge(m, src)
}
func (m *EventActivityChanged) XXX_Size() int {
	return m.Size()
}
func (m *EventActivityChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_EventActivityChanged.DiscardUnknown(m)
}

var xxx_messageInfo_EventActivityChanged proto.InternalMessageInfo

func (m *EventActivityChanged) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventActivityChanged) GetActiveNow() bool {
	if m != nil {
		return m.ActiveNow
	}
	return false
}

type EventUpdateLimitsResetUsed struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *EventUpdateLimitsResetUsed) Reset()         { *m = EventUpdateLimitsResetUsed{} }
func (m *EventUpdateLimitsResetUsed) String() string { return proto.CompactTextString(m) }
func (*EventUpdateLimitsResetUsed) ProtoMessage()    {}
func (*EventUpdateLimitsResetUsed) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{2}
}
func (m *EventUpdateLimitsResetUsed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventUpdateLimitsResetUsed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventUpdateLimitsResetUsed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventUpdateLimitsResetUsed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateLimitsResetUsed.Merge(m, src)
}
func (m *EventUpdateLimitsResetUsed) XXX_Size() int {
	return m.Size()
}
func (m *EventUpdateLimitsResetUsed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateLimitsResetUsed.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateLimitsResetUsed proto.InternalMessageInfo

func (m *EventUpdateLimitsResetUsed) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type EventAutoPayFailed struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *EventAutoPayFailed) Reset()         { *m = EventAutoPayFailed{} }
func (m *EventAutoPayFailed) String() string { return proto.CompactTextString(m) }
func (*EventAutoPayFailed) ProtoMessage()    {}
func (*EventAutoPayFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{3}
}
func (m *EventAutoPayFailed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAutoPayFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAutoPayFailed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAutoPayFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAutoPayFailed.Merge(m, src)
}
func (m *EventAutoPayFailed) XXX_Size() int {
	return m.Size()
}
func (m *EventAutoPayFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAutoPayFailed.DiscardUnknown(m)
}

var xxx_messageInfo_EventAutoPayFailed proto.InternalMessageInfo

func (m *EventAutoPayFailed) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventAutoPayFailed) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EventBuyVpn struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewLimit uint64 `protobuf:"varint,2,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
	Used     uint64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Total    uint64 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *EventBuyVpn) Reset()         { *m = EventBuyVpn{} }
func (m *EventBuyVpn) String() string { return proto.CompactTextString(m) }
func (*EventBuyVpn) ProtoMessage()    {}
func (*EventBuyVpn) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{4}
}
func (m *EventBuyVpn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBuyVpn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBuyVpn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBuyVpn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBuyVpn.Merge(m, src)
}
func (m *EventBuyVpn) XXX_Size() int {
	return m.Size()
}
func (m *EventBuyVpn) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBuyVpn.DiscardUnknown(m)
}

var xxx_messageInfo_EventBuyVpn proto.InternalMessageInfo

func (m *EventBuyVpn) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventBuyVpn) GetNewLimit() uint64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *EventBuyVpn) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *EventBuyVpn) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type EventBuyStorage struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewLimit uint64 `protobuf:"varint,2,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
	Used     uint64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Total    uint64 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *EventBuyStorage) Reset()         { *m = EventBuyStorage{} }
func (m *EventBuyStorage) String() string { return proto.CompactTextString(m) }
func (*EventBuyStorage) ProtoMessage()    {}
func (*EventBuyStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{5}
}
func (m *EventBuyStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBuyStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBuyStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBuyStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBuyStorage.Merge(m, src)
}
func (m *EventBuyStorage) XXX_Size() int {
	return m.Size()
}
func (m *EventBuyStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBuyStorage.DiscardUnknown(m)
}

var xxx_messageInfo_EventBuyStorage proto.InternalMessageInfo

func (m *EventBuyStorage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventBuyStorage) GetNewLimit() uint64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *EventBuyStorage) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *EventBuyStorage) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type EventGiveUpStorage struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewLimit uint64 `protobuf:"varint,2,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
	Used     uint64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
}

func (m *EventGiveUpStorage) Reset()         { *m = EventGiveUpStorage{} }
func (m *EventGiveUpStorage) String() string { return proto.CompactTextString(m) }
func (*EventGiveUpStorage) ProtoMessage()    {}
func (*EventGiveUpStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{6}
}
func (m *EventGiveUpStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventGiveUpStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventGiveUpStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventGiveUpStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGiveUpStorage.Merge(m, src)
}
func (m *EventGiveUpStorage) XXX_Size() int {
	return m.Size()
}
func (m *EventGiveUpStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGiveUpStorage.DiscardUnknown(m)
}

var xxx_messageInfo_EventGiveUpStorage proto.InternalMessageInfo

func (m *EventGiveUpStorage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventGiveUpStorage) GetNewLimit() uint64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *EventGiveUpStorage) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type EventBuyExtraImStorage struct {
	Address  string    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewLimit uint64    `protobuf:"varint,2,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
	Total    uint64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ExpireAt time.Time `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3,stdtime" json:"expire_at"`
}

func (m *EventBuyExtraImStorage) Reset()         { *m = EventBuyExtraImStorage{} }
func (m *EventBuyExtraImStorage) String() string { return proto.CompactTextString(m) }
func (*EventBuyExtraImStorage) ProtoMessage()    {}
func (*EventBuyExtraImStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{7}
}
func (m *EventBuyExtraImStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBuyExtraImStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBuyExtraImStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBuyExtraImStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBuyExtraImStorage.Merge(m, src)
}
func (m *EventBuyExtraImStorage) XXX_Size() int {
	return m.Size()
}
func (m *EventBuyExtraImStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBuyExtraImStorage.DiscardUnknown(m)
}

var xxx_messageInfo_EventBuyExtraImStorage proto.InternalMessageInfo

func (m *EventBuyExtraImStorage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventBuyExtraImStorage) GetNewLimit() uint64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *EventBuyExtraImStorage) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *EventBuyExtraImStorage) GetExpireAt() time.Time {
	if m != nil {
		return m.ExpireAt
	}
	return time.Time{}
}

type EventGiveUpImStorage struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NewLimit uint64 `protobuf:"varint,2,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
}

func (m *EventGiveUpImStorage) Reset()         { *m = EventGiveUpImStorage{} }
func (m *EventGiveUpImStorage) String() string { return proto.CompactTextString(m) }
func (*EventGiveUpImStorage) ProtoMessage()    {}
func (*EventGiveUpImStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{8}
}
func (m *EventGiveUpImStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventGiveUpImStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventGiveUpImStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventGiveUpImStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGiveUpImStorage.Merge(m, src)
}
func (m *EventGiveUpImStorage) XXX_Size() int {
	return m.Size()
}
func (m *EventGiveUpImStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGiveUpImStorage.DiscardUnknown(m)
}

var xxx_messageInfo_EventGiveUpImStorage proto.InternalMessageInfo

func (m *EventGiveUpImStorage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventGiveUpImStorage) GetNewLimit() uint64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

type EventImAutoPayFailed struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *EventImAutoPayFailed) Reset()         { *m = EventImAutoPayFailed{} }
func (m *EventImAutoPayFailed) String() string { return proto.CompactTextString(m) }
func (*EventImAutoPayFailed) ProtoMessage()    {}
func (*EventImAutoPayFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ba350bd2fbdb11, []int{9}
}
func (m *EventImAutoPayFailed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventImAutoPayFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventImAutoPayFailed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventImAutoPayFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventImAutoPayFailed.Merge(m, src)
}
func (m *EventImAutoPayFailed) XXX_Size() int {
	return m.Size()
}
func (m *EventImAutoPayFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventImAutoPayFailed.DiscardUnknown(m)
}

var xxx_messageInfo_EventImAutoPayFailed proto.InternalMessageInfo

func (m *EventImAutoPayFailed) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventImAutoPayFailed) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*EventPayTariff)(nil), "artery.profile.v1beta1.EventPayTariff")
	proto.RegisterType((*EventActivityChanged)(nil), "artery.profile.v1beta1.EventActivityChanged")
	proto.RegisterType((*EventUpdateLimitsResetUsed)(nil), "artery.profile.v1beta1.EventUpdateLimitsResetUsed")
	proto.RegisterType((*EventAutoPayFailed)(nil), "artery.profile.v1beta1.EventAutoPayFailed")
	proto.RegisterType((*EventBuyVpn)(nil), "artery.profile.v1beta1.EventBuyVpn")
	proto.RegisterType((*EventBuyStorage)(nil), "artery.profile.v1beta1.EventBuyStorage")
	proto.RegisterType((*EventGiveUpStorage)(nil), "artery.profile.v1beta1.EventGiveUpStorage")
	proto.RegisterType((*EventBuyExtraImStorage)(nil), "artery.profile.v1beta1.EventBuyExtraImStorage")
	proto.RegisterType((*EventGiveUpImStorage)(nil), "artery.profile.v1beta1.EventGiveUpImStorage")
	proto.RegisterType((*EventImAutoPayFailed)(nil), "artery.profile.v1beta1.EventImAutoPayFailed")
}

func init() {
	proto.RegisterFile("artery/profile/v1beta1/events.proto", fileDescriptor_80ba350bd2fbdb11)
}

var fileDescriptor_80ba350bd2fbdb11 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0x89, 0x03, 0xf1, 0x94, 0xa7, 0x15, 0x55, 0x56, 0x10, 0x4e, 0xe4, 0x6e, 0x22, 0x21,
	0x6c, 0x15, 0x24, 0xf6, 0x09, 0xb4, 0x55, 0x25, 0x1e, 0x95, 0x49, 0x58, 0xb0, 0x89, 0x26, 0xc9,
	0x8d, 0x3b, 0x22, 0xf6, 0x58, 0x33, 0xd7, 0x49, 0xfc, 0x17, 0xfd, 0x0c, 0x3e, 0xa5, 0xcb, 0x6e,
	0x90, 0x58, 0x01, 0x4a, 0x7e, 0x04, 0x65, 0xc6, 0x21, 0x45, 0x42, 0x59, 0x10, 0xba, 0xf3, 0xbd,
	0x3e, 0x73, 0x1e, 0x77, 0x1e, 0xe4, 0x80, 0x0a, 0x04, 0x91, 0x07, 0xa9, 0xe0, 0x63, 0x36, 0x81,
	0x60, 0x7a, 0x38, 0x00, 0xa4, 0x87, 0x01, 0x4c, 0x21, 0x41, 0xe9, 0xa7, 0x82, 0x23, 0xb7, 0xf7,
	0x35, 0xc8, 0x2f, 0x40, 0x7e, 0x01, 0xaa, 0xd7, 0x22, 0x1e, 0x71, 0x05, 0x09, 0x56, 0x5f, 0x1a,
	0x5d, 0x6f, 0x44, 0x9c, 0x47, 0x13, 0x08, 0x54, 0x35, 0xc8, 0xc6, 0x01, 0xb2, 0x18, 0x24, 0xd2,
	0x38, 0xd5, 0x00, 0xef, 0xab, 0x41, 0xee, 0x1f, 0xad, 0xf8, 0xcf, 0x68, 0xde, 0xa5, 0x82, 0x8d,
	0xc7, 0xb6, 0x43, 0xee, 0xd0, 0xd1, 0x48, 0x80, 0x94, 0x8e, 0xd1, 0x34, 0x5a, 0x56, 0xb8, 0x2e,
	0xed, 0x36, 0xb1, 0x60, 0x9e, 0x32, 0x01, 0x7d, 0x8a, 0xce, 0xad, 0xa6, 0xd1, 0xda, 0x7b, 0x5e,
	0xf7, 0xb5, 0x82, 0xbf, 0x56, 0xf0, 0xbb, 0x6b, 0x85, 0x4e, 0xf5, 0xf2, 0x7b, 0xa3, 0x74, 0xf1,
	0xa3, 0x61, 0x84, 0x55, 0xbd, 0xac, 0x8d, 0x76, 0x8d, 0x54, 0x90, 0x23, 0x9d, 0x38, 0xe5, 0xa6,
	0xd1, 0x32, 0x43, 0x5d, 0xd8, 0x07, 0xe4, 0xde, 0x90, 0xc7, 0x31, 0x93, 0x92, 0xf1, 0xa4, 0x8f,
	0xdc, 0x31, 0x9b, 0xe5, 0x96, 0x15, 0xde, 0xdd, 0x34, 0xbb, 0xdc, 0x7e, 0x4a, 0x1e, 0x5d, 0x03,
	0xd1, 0x98, 0x67, 0x09, 0x3a, 0x95, 0x66, 0xb9, 0x65, 0x86, 0x0f, 0x37, 0x3f, 0xda, 0xaa, 0xef,
	0xbd, 0x27, 0x35, 0x15, 0xab, 0x3d, 0x44, 0x36, 0x65, 0x98, 0xbf, 0x3a, 0xa7, 0x49, 0x04, 0xa3,
	0x2d, 0xe1, 0x9e, 0x10, 0x42, 0x57, 0x60, 0xe8, 0x27, 0x7c, 0xa6, 0xd2, 0x55, 0x43, 0x4b, 0x77,
	0xde, 0xf1, 0x99, 0xf7, 0x92, 0xd4, 0x15, 0x61, 0x2f, 0x1d, 0x51, 0x84, 0x37, 0x2c, 0x66, 0x28,
	0x43, 0x90, 0x80, 0x3d, 0xb9, 0x8d, 0xd6, 0x7b, 0x4d, 0x6c, 0x6d, 0x24, 0x43, 0x7e, 0x46, 0xf3,
	0x63, 0xca, 0x26, 0x5b, 0x6d, 0xd4, 0x48, 0x05, 0x84, 0xe0, 0x42, 0x39, 0xb0, 0x42, 0x5d, 0x78,
	0x09, 0xd9, 0x53, 0x2c, 0x9d, 0x2c, 0xff, 0x98, 0x26, 0x5b, 0x96, 0x3f, 0x26, 0x56, 0x02, 0xb3,
	0xfe, 0x64, 0xe5, 0x4f, 0x51, 0x98, 0x61, 0x35, 0x81, 0x99, 0xf2, 0x6b, 0xdb, 0xc4, 0xcc, 0x24,
	0x8c, 0x8a, 0xd9, 0xab, 0xef, 0xcd, 0x86, 0x98, 0xd7, 0x36, 0xc4, 0x13, 0xe4, 0xc1, 0x5a, 0xef,
	0x03, 0x72, 0x41, 0x23, 0xb8, 0x79, 0xcd, 0x7e, 0x31, 0xa9, 0x13, 0x36, 0x85, 0x5e, 0xfa, 0xff,
	0x65, 0xbd, 0x2f, 0x06, 0xd9, 0x5f, 0xa7, 0x3a, 0x9a, 0xa3, 0xa0, 0xa7, 0xf1, 0x8e, 0x2a, 0x7f,
	0x0d, 0xf2, 0xe7, 0x35, 0xa9, 0xfc, 0xcb, 0x35, 0xf1, 0xde, 0x16, 0xc7, 0x57, 0xcf, 0x62, 0x57,
	0x9f, 0xde, 0x71, 0x41, 0x77, 0x1a, 0xef, 0x74, 0x0c, 0x3b, 0x27, 0x97, 0x0b, 0xd7, 0xb8, 0x5a,
	0xb8, 0xc6, 0xcf, 0x85, 0x6b, 0x5c, 0x2c, 0xdd, 0xd2, 0xd5, 0xd2, 0x2d, 0x7d, 0x5b, 0xba, 0xa5,
	0x4f, 0xcf, 0x22, 0x86, 0xe7, 0xd9, 0xc0, 0x1f, 0xf2, 0x38, 0xd0, 0x2f, 0x54, 0x02, 0x38, 0xe3,
	0xe2, 0xf3, 0xaa, 0x12, 0xc1, 0xfc, 0xf7, 0xa3, 0x86, 0x79, 0x0a, 0x72, 0x70, 0x5b, 0xcd, 0xe1,
	0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x0d, 0xb3, 0x8a, 0xf3, 0x04, 0x00, 0x00,
}

func (m *EventPayTariff) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventPayTariff) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventPayTariff) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommissionAmount) > 0 {
		dAtA2 := make([]byte, len(m.CommissionAmount)*10)
		var j1 int
		for _, num := range m.CommissionAmount {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintEvents(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CommissionTo) > 0 {
		for iNdEx := len(m.CommissionTo) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CommissionTo[iNdEx])
			copy(dAtA[i:], m.CommissionTo[iNdEx])
			i = encodeVarintEvents(dAtA, i, uint64(len(m.CommissionTo[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Total != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x18
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpireAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintEvents(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventActivityChanged) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventActivityChanged) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventActivityChanged) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActiveNow {
		i--
		if m.ActiveNow {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventUpdateLimitsResetUsed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventUpdateLimitsResetUsed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventUpdateLimitsResetUsed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventAutoPayFailed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAutoPayFailed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAutoPayFailed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBuyVpn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBuyVpn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBuyVpn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x20
	}
	if m.Used != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Used))
		i--
		dAtA[i] = 0x18
	}
	if m.NewLimit != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBuyStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBuyStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBuyStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x20
	}
	if m.Used != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Used))
		i--
		dAtA[i] = 0x18
	}
	if m.NewLimit != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventGiveUpStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventGiveUpStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventGiveUpStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Used != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Used))
		i--
		dAtA[i] = 0x18
	}
	if m.NewLimit != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBuyExtraImStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBuyExtraImStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBuyExtraImStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpireAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintEvents(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2a
	if m.Total != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x20
	}
	if m.NewLimit != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventGiveUpImStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventGiveUpImStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventGiveUpImStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewLimit != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NewLimit))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventImAutoPayFailed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventImAutoPayFailed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventImAutoPayFailed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventPayTariff) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireAt)
	n += 1 + l + sovEvents(uint64(l))
	if m.Total != 0 {
		n += 1 + sovEvents(uint64(m.Total))
	}
	if len(m.CommissionTo) > 0 {
		for _, s := range m.CommissionTo {
			l = len(s)
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	if len(m.CommissionAmount) > 0 {
		l = 0
		for _, e := range m.CommissionAmount {
			l += sovEvents(uint64(e))
		}
		n += 1 + sovEvents(uint64(l)) + l
	}
	return n
}

func (m *EventActivityChanged) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.ActiveNow {
		n += 2
	}
	return n
}

func (m *EventUpdateLimitsResetUsed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventAutoPayFailed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventBuyVpn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.NewLimit != 0 {
		n += 1 + sovEvents(uint64(m.NewLimit))
	}
	if m.Used != 0 {
		n += 1 + sovEvents(uint64(m.Used))
	}
	if m.Total != 0 {
		n += 1 + sovEvents(uint64(m.Total))
	}
	return n
}

func (m *EventBuyStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.NewLimit != 0 {
		n += 1 + sovEvents(uint64(m.NewLimit))
	}
	if m.Used != 0 {
		n += 1 + sovEvents(uint64(m.Used))
	}
	if m.Total != 0 {
		n += 1 + sovEvents(uint64(m.Total))
	}
	return n
}

func (m *EventGiveUpStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.NewLimit != 0 {
		n += 1 + sovEvents(uint64(m.NewLimit))
	}
	if m.Used != 0 {
		n += 1 + sovEvents(uint64(m.Used))
	}
	return n
}

func (m *EventBuyExtraImStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.NewLimit != 0 {
		n += 1 + sovEvents(uint64(m.NewLimit))
	}
	if m.Total != 0 {
		n += 1 + sovEvents(uint64(m.Total))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpireAt)
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func (m *EventGiveUpImStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.NewLimit != 0 {
		n += 1 + sovEvents(uint64(m.NewLimit))
	}
	return n
}

func (m *EventImAutoPayFailed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventPayTariff) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventPayTariff: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventPayTariff: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpireAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissionTo = append(m.CommissionTo, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CommissionAmount = append(m.CommissionAmount, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvents
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEvents
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEvents
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.CommissionAmount) == 0 {
					m.CommissionAmount = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvents
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CommissionAmount = append(m.CommissionAmount, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissionAmount", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventActivityChanged) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventActivityChanged: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventActivityChanged: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveNow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ActiveNow = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventUpdateLimitsResetUsed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventUpdateLimitsResetUsed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventUpdateLimitsResetUsed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAutoPayFailed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAutoPayFailed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAutoPayFailed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBuyVpn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBuyVpn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBuyVpn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLimit", wireType)
			}
			m.NewLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			m.Used = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Used |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBuyStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBuyStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBuyStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLimit", wireType)
			}
			m.NewLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			m.Used = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Used |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventGiveUpStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventGiveUpStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventGiveUpStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLimit", wireType)
			}
			m.NewLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			m.Used = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Used |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBuyExtraImStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBuyExtraImStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBuyExtraImStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLimit", wireType)
			}
			m.NewLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpireAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventGiveUpImStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventGiveUpImStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventGiveUpImStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLimit", wireType)
			}
			m.NewLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventImAutoPayFailed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventImAutoPayFailed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventImAutoPayFailed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
