// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: artery/earning/v1beta1/events.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Deprecated: Do not use.
type EventStartPaying struct {
}

func (m *EventStartPaying) Reset()         { *m = EventStartPaying{} }
func (m *EventStartPaying) String() string { return proto.CompactTextString(m) }
func (*EventStartPaying) ProtoMessage()    {}
func (*EventStartPaying) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04fe06e4f2f6ab7, []int{0}
}
func (m *EventStartPaying) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventStartPaying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventStartPaying.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventStartPaying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStartPaying.Merge(m, src)
}
func (m *EventStartPaying) XXX_Size() int {
	return m.Size()
}
func (m *EventStartPaying) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStartPaying.DiscardUnknown(m)
}

var xxx_messageInfo_EventStartPaying proto.InternalMessageInfo

// Deprecated: Do not use.
type EventEarn struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Vpn     uint64 `protobuf:"varint,2,opt,name=vpn,proto3" json:"vpn,omitempty"`
	Storage uint64 `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (m *EventEarn) Reset()         { *m = EventEarn{} }
func (m *EventEarn) String() string { return proto.CompactTextString(m) }
func (*EventEarn) ProtoMessage()    {}
func (*EventEarn) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04fe06e4f2f6ab7, []int{1}
}
func (m *EventEarn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventEarn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventEarn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventEarn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEarn.Merge(m, src)
}
func (m *EventEarn) XXX_Size() int {
	return m.Size()
}
func (m *EventEarn) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEarn.DiscardUnknown(m)
}

var xxx_messageInfo_EventEarn proto.InternalMessageInfo

func (m *EventEarn) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventEarn) GetVpn() uint64 {
	if m != nil {
		return m.Vpn
	}
	return 0
}

func (m *EventEarn) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

// Deprecated: Do not use.
type EventFinishPaying struct {
}

func (m *EventFinishPaying) Reset()         { *m = EventFinishPaying{} }
func (m *EventFinishPaying) String() string { return proto.CompactTextString(m) }
func (*EventFinishPaying) ProtoMessage()    {}
func (*EventFinishPaying) Descriptor() ([]byte, []int) {
	return fileDescriptor_c04fe06e4f2f6ab7, []int{2}
}
func (m *EventFinishPaying) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFinishPaying) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFinishPaying.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventFinishPaying) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFinishPaying.Merge(m, src)
}
func (m *EventFinishPaying) XXX_Size() int {
	return m.Size()
}
func (m *EventFinishPaying) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFinishPaying.DiscardUnknown(m)
}

var xxx_messageInfo_EventFinishPaying proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EventStartPaying)(nil), "artery.earning.v1beta1.EventStartPaying")
	proto.RegisterType((*EventEarn)(nil), "artery.earning.v1beta1.EventEarn")
	proto.RegisterType((*EventFinishPaying)(nil), "artery.earning.v1beta1.EventFinishPaying")
}

func init() {
	proto.RegisterFile("artery/earning/v1beta1/events.proto", fileDescriptor_c04fe06e4f2f6ab7)
}

var fileDescriptor_c04fe06e4f2f6ab7 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe3, 0x16, 0x81, 0xea, 0xa9, 0x64, 0x28, 0x9e, 0xac, 0xaa, 0x2c, 0x5d, 0x88, 0x55,
	0xb1, 0x31, 0x22, 0x15, 0x56, 0x54, 0xc4, 0xc2, 0xe6, 0xd0, 0x53, 0x6a, 0x21, 0xce, 0xd1, 0xf9,
	0x08, 0xe4, 0x2d, 0x78, 0x2c, 0xc6, 0x8e, 0x8c, 0x28, 0x79, 0x11, 0x64, 0xb7, 0xa5, 0xdb, 0xfd,
	0xbf, 0x3e, 0xfd, 0xa7, 0x4f, 0x5e, 0x5a, 0x62, 0xa0, 0xd6, 0x80, 0x25, 0x74, 0x58, 0x99, 0x66,
	0x51, 0x02, 0xdb, 0x85, 0x81, 0x06, 0x90, 0x43, 0x51, 0x93, 0x67, 0x9f, 0x4f, 0x76, 0x50, 0xb1,
	0x87, 0x8a, 0x3d, 0x34, 0x9b, 0xc8, 0xf1, 0x32, 0x72, 0x8f, 0x6c, 0x89, 0x1f, 0x6c, 0xeb, 0xb0,
	0xba, 0x19, 0x28, 0x31, 0x7b, 0x92, 0xa3, 0xd4, 0x2f, 0x2d, 0x61, 0xae, 0xe4, 0x99, 0x5d, 0xaf,
	0x09, 0x42, 0x50, 0x62, 0x2a, 0xe6, 0xa3, 0xd5, 0x21, 0xe6, 0x63, 0x39, 0x6c, 0x6a, 0x54, 0x83,
	0xa9, 0x98, 0x9f, 0xac, 0xe2, 0x19, 0xd9, 0xc0, 0x9e, 0x6c, 0x05, 0x6a, 0x98, 0xda, 0x43, 0x4c,
	0xb3, 0x17, 0xf2, 0x3c, 0xcd, 0xde, 0x39, 0x74, 0x61, 0x73, 0xfc, 0x77, 0x7b, 0xff, 0xdd, 0x69,
	0xb1, 0xed, 0xb4, 0xf8, 0xed, 0xb4, 0xf8, 0xea, 0x75, 0xb6, 0xed, 0x75, 0xf6, 0xd3, 0xeb, 0xec,
	0xf9, 0xaa, 0x72, 0xbc, 0x79, 0x2f, 0x8b, 0x17, 0xff, 0x66, 0x76, 0x12, 0x08, 0xfc, 0xe1, 0xe9,
	0x35, 0x26, 0x32, 0x9f, 0xff, 0xde, 0xdc, 0xd6, 0x10, 0xca, 0xd3, 0xe4, 0x7b, 0xfd, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0xe5, 0x81, 0xa3, 0x16, 0x01, 0x00, 0x00,
}

func (m *EventStartPaying) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventStartPaying) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventStartPaying) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *EventEarn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventEarn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventEarn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Storage != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Storage))
		i--
		dAtA[i] = 0x18
	}
	if m.Vpn != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Vpn))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventFinishPaying) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFinishPaying) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventFinishPaying) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventStartPaying) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *EventEarn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Vpn != 0 {
		n += 1 + sovEvents(uint64(m.Vpn))
	}
	if m.Storage != 0 {
		n += 1 + sovEvents(uint64(m.Storage))
	}
	return n
}

func (m *EventFinishPaying) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventStartPaying) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventStartPaying: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventStartPaying: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventEarn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventEarn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventEarn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vpn", wireType)
			}
			m.Vpn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vpn |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Storage", wireType)
			}
			m.Storage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Storage |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventFinishPaying) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFinishPaying: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFinishPaying: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
